### ISSUE TITLE
Error while using shaded artifact in release 1.3.7

### ISSUE THREAD

**Issue by mkelkarbv** [oracle/oci-java-sdk#104]
I followed the steps documented here - https://docs.cloud.oracle.com/iaas/Content/API/SDKDocs/javasdkexamples.htm for using shaded jar. 
Regular jar works fine as described, but I am having problems with shaded version. 

This is exact command 
```java -cp examples:shaded/lib/oci-java-sdk-full-shaded-1.3.7.jar:shaded/third-party/lib/* ObjectStorageSyncExample```

Output - 
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.NoClassDefFoundError: shaded/com/oracle/oci/javasdk/org/glassfish/jersey/client/spi/ConnectorProvider
	at com.oracle.bmc.http.internal.RestClientFactoryBuilder.<clinit>(RestClientFactoryBuilder.java:24)
	at com.oracle.bmc.objectstorage.ObjectStorageClient.<init>(ObjectStorageClient.java:178)
	at com.oracle.bmc.objectstorage.ObjectStorageClient.<init>(ObjectStorageClient.java:141)
	at com.oracle.bmc.objectstorage.ObjectStorageClient.<init>(ObjectStorageClient.java:113)
	at com.oracle.bmc.objectstorage.ObjectStorageClient.<init>(ObjectStorageClient.java:88)
	at com.oracle.bmc.objectstorage.ObjectStorageClient.<init>(ObjectStorageClient.java:65)
	at com.oracle.bmc.objectstorage.ObjectStorageClient.<init>(ObjectStorageClient.java:51)
	at com.oracle.bmc.objectstorage.ObjectStorageClient.<init>(ObjectStorageClient.java:40)
	at ObjectStorageSyncExample.main(ObjectStorageSyncExample.java:26)
Caused by: java.lang.ClassNotFoundException: shaded.com.oracle.oci.javasdk.org.glassfish.jersey.client.spi.ConnectorProvider
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 9 more```

**Comment by mkelkarbv** [comment]
version 1.3.4 is working fine....

**Comment by andy-miles** [comment]
[Release 1.4.3](https://github.com/oracle/oci-java-sdk/releases/tag/v1.4.3) includes an updated shaded fat jar.  It now includes the Jersey client dependencies in order to resolve the error you cited above.  Please download this version and copy the following jars from the release distribution to your project:

- shaded/lib/oci-java-sdk-full-shaded-1.4.3.jar
- shaded/third-party/lib/bcpkix-jdk15on-1.60.jar
- shaded/third-party/lib/bcprov-jdk15on-1.60.jar
- shaded/third-party/lib/slf4j-api-1.7.25.jar

If you continue to experience issues, please reply to this issue.

Thank you.
