### ISSUE TITLE
CreateInstanceExample fails with BmcException

### ISSUE THREAD

**Issue by aalmiray** [oracle/oci-java-sdk#120]
Attempting to run the `CreateInstanceExample.java` example with version `1.5.2` results in

    Caused by: com.oracle.bmc.model.BmcException: (400, InvalidParameter, false) routeRules[0].networkEntityId may not be null (opc-request-id: 25744B636...)
            at com.oracle.bmc.http.internal.ResponseHelper.throwIfNotSuccessful(ResponseHelper.java:120)
            at com.oracle.bmc.http.internal.ResponseConversionFunctionFactory$ValidatingParseResponseFunction.apply(ResponseConversionFunctionFactory.java:86)
            at com.oracle.bmc.http.internal.ResponseConversionFunctionFactory$ValidatingParseResponseFunction.apply(ResponseConversionFunctionFactory.java:82)
            at com.oracle.bmc.core.internal.http.UpdateRouteTableConverter$1.apply(UpdateRouteTableConverter.java:70)
            at com.oracle.bmc.core.internal.http.UpdateRouteTableConverter$1.apply(UpdateRouteTableConverter.java:55)
            at com.oracle.bmc.core.VirtualNetworkClient.updateRouteTable(VirtualNetworkClient.java:3325)

**Comment by recursivecodes** [comment]
Lines 290-293 should be replaced with this to resolve this issue:

```
RouteRule.builder()
    //.cidrBlock("0.0.0.0/0") Deprecated - use destination()
    .destination("0.0.0.0/0")
    .destinationType(RouteRule.DestinationType.CidrBlock)
    .networkEntityId(internetGateway.getId())
    .build();
```

**Comment by andy-miles** [comment]
Since the updated example has been merged, I'm closing this issue.
