### ISSUE TITLE
java.lang.NoSuchMethodError: com.oracle.bmc.ClientConfiguration.getRetryConfiguration

### ISSUE THREAD

**Issue by ekumen** [oracle/oci-java-sdk#142]
Hi, I see following error using `oci-java-sdk shaded version 1.5.15`.  Does anyone else see it too?
DEBUG c.o.b.h.s.i.PEMFileRSAPrivateKeySupplier  - Initializing private key
Exception in thread "main" java.lang.NoSuchMethodError: com.oracle.bmc.ClientConfiguration.getRetryConfiguration()Lcom/oracle/bmc/retrier/RetryConfiguration;
	at com.oracle.bmc.objectstorage.ObjectStorageClient.<init>(ObjectStorageClient.java:247)
	at com.oracle.bmc.objectstorage.ObjectStorageClient.<init>(ObjectStorageClient.java:179)
	at com.oracle.bmc.objectstorage.ObjectStorageClient.<init>(ObjectStorageClient.java:144)
	at com.oracle.bmc.objectstorage.ObjectStorageClient.<init>(ObjectStorageClient.java:116)
	at com.oracle.bmc.objectstorage.ObjectStorageClient.<init>(ObjectStorageClient.java:91)
	at com.oracle.bmc.objectstorage.ObjectStorageClient.<init>(ObjectStorageClient.java:68)
	at com.oracle.bmc.objectstorage.ObjectStorageClient.<init>(ObjectStorageClient.java:54)

**Comment by ekumen** [comment]
Please ignore this error. This is because I have two shaded versions in the classpath.
