### ISSUE TITLE
Getting 411 error The Content-Length header is required while uploading mp4 video file to Object Store

### ISSUE THREAD

**Issue by rsingareddy** [oracle/oci-java-sdk#151]
Here is the code: 
```
String configurationFilePath = "/config";
	String profile = "DEFAULT";
	AuthenticationDetailsProvider provider = null;
	private String compartmentId;

	public ObjectStorageUtil() {
		try {
			provider = new ConfigFileAuthenticationDetailsProvider(configurationFilePath, profile);
			ConfigFile config = ConfigFileReader.parse(configurationFilePath);
			compartmentId = config.get("custom_compartment_id");
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	public void putObject(String bucket, String object, Region region, InputStream stream, long contentLength) {
		ObjectStorage client = new ObjectStorageClient(provider);
		client.setRegion(region);
		System.out.println("Getting the namespace.");
		GetNamespaceResponse namespaceResponse = client.getNamespace(GetNamespaceRequest.builder().build());
		String namespaceName = namespaceResponse.getValue();

		System.out.println("Creating the source bucket.");

		GetBucketRequest request = GetBucketRequest.builder().namespaceName(namespaceName).bucketName(bucket).build();

		System.out.println("Fetching bucket details");
		GetBucketResponse response = client.getBucket(request);
		try {
			if (response == null || response.getBucket() == null
					|| response.getBucket().getName().trim().equalsIgnoreCase("")) {
				CreateBucketDetails createSourceBucketDetails = CreateBucketDetails.builder()
						.compartmentId(compartmentId).name(bucket).build();

				CreateBucketRequest createSourceBucketRequest = CreateBucketRequest.builder()
						.namespaceName(namespaceName).createBucketDetails(createSourceBucketDetails).build();
				client.createBucket(createSourceBucketRequest);
			}
		} catch (com.oracle.bmc.model.BmcException ex) {
			ex.printStackTrace();
		}

		System.out.println("Creating the source object");

		PutObjectRequest putObjectRequest = PutObjectRequest.builder().namespaceName(namespaceName).bucketName(bucket)
				.objectName(object).contentLength(contentLength).putObjectBody(stream).build();

		UploadConfiguration uploadConfiguration = UploadConfiguration.builder().minimumLengthForMultipartUpload(10)
				.lengthPerUploadPart(10).build();
		UploadManager uploadManager = new UploadManager(client, uploadConfiguration) {

		};

		UploadRequest uploadRequest = UploadRequest.builder(stream, contentLength).progressReporter(null)
				.build(putObjectRequest);

		UploadResponse uploadResponse = uploadManager.upload(uploadRequest);
		
		GetObjectResponse getResponse = 
				client.getObject( 
				GetObjectRequest.builder() 
				.namespaceName(namespaceName) 
				.bucketName(bucket) 
				.objectName(object) 
				.build()); 
		
		System.out.println(getResponse.getContentType());

	}
```

______________________________________________________________________________________________________
We are receiving following error

 2019-08-21 08:32:19 ERROR stderr:71 - com.oracle.bmc.model.BmcException: (411, ContentLengthRequired, false) The Content-Length header is required (opc-request-id: iad-0:pvpIeG6APo4JcZLNq8eoi/q81DV46ihJTes9lUK17FCpRJnk0GpjY7YkNhuELc7U)  2019-08-21 08:32:19 ERROR stderr:71 -   at com.oracle.bmc.http.internal.ResponseHelper.throwIfNotSuccessful(ResponseHelper.java:127)  2019-08-21 08:32:19 ERROR stderr:71 -   at com.oracle.bmc.http.internal.ResponseConversionFunctionFactory$ValidatingParseResponseFunction.apply(ResponseConversionFunctionFactory.java:86)  2019-08-21 08:32:19 ERROR stderr:71 -   at com.oracle.bmc.http.internal.ResponseConversionFunctionFactory$ValidatingParseResponseFunction.apply(ResponseConversionFunctionFactory.java:82)  2019-08-21 08:32:19 ERROR stderr:71 -   at com.oracle.bmc.objectstorage.internal.http.PutObjectConverter$1.apply(PutObjectConverter.java:112)  2019-08-21 08:32:19 ERROR stderr:71 -   at com.oracle.bmc.objectstorage.internal.http.PutObjectConverter$1.apply(PutObjectConverter.java:102)  2019-08-21 08:32:19 ERROR stderr:71 -   at com.oracle.bmc.objectstorage.ObjectStorageClient.lambda$null$56(ObjectStorageClient.java:1234)  2019-08-21 08:32:19 ERROR stderr:71 -   at com.oracle.bmc.retrier.BmcGenericRetrier.lambda$execute$0(BmcGenericRetrier.java:50)  2019-08-21 08:32:19 ERROR stderr:71 -   at com.oracle.bmc.waiter.GenericWaiter.execute(GenericWaiter.java:54)  2019-08-21 08:32:19 ERROR stderr:71 -   at com.oracle.bmc.retrier.BmcGenericRetrier.execute(BmcGenericRetrier.java:46)  2019-08-21 08:32:19 ERROR stderr:71 -   at com.oracle.bmc.objectstorage.ObjectStorageClient.lambda$putObject$57(ObjectStorageClient.java:1226)  2019-08-21 08:32:19 ERROR stderr:71 -   at com.oracle.bmc.retrier.BmcGenericRetrier.lambda$execute$0(BmcGenericRetrier.java:50)  2019-08-21 08:32:19 ERROR stderr:71 -   at com.oracle.bmc.waiter.GenericWaiter.execute(GenericWaiter.java:54)  2019-08-21 08:32:19 ERROR stderr:71 -   at com.oracle.bmc.retrier.BmcGenericRetrier.execute(BmcGenericRetrier.java:46)  2019-08-21 08:32:19 ERROR stderr:71 -   at com.oracle.bmc.objectstorage.ObjectStorageClient.putObject(ObjectStorageClient.java:1220)  2019-08-21 08:32:19 ERROR stderr:71 -   at com.oracle.bmc.objectstorage.transfer.internal.SimpleRetry$1.apply(SimpleRetry.java:36)  2019-08-21 08:32:19 ERROR stderr:71 -   at com.oracle.bmc.objectstorage.transfer.internal.SimpleRetry$1.apply(SimpleRetry.java:28)  2019-08-21 08:32:19 ERROR stderr:71 -   at com.oracle.bmc.objectstorage.transfer.UploadManager.singleUpload(UploadManager.java:115)  2019-08-21 08:32:19 ERROR stderr:71 -   at com.oracle.bmc.objectstorage.transfer.UploadManager.upload(UploadManager.java:77)
-- | --

We are uploading SimpleVideo.mp4 file.
[SampleVideo.zip](https://github.com/oracle/oci-java-sdk/files/3537454/SampleVideo.zip)

**Comment by rsingareddy** [comment]
2019-08-29 01:05:09 ERROR stderr:71 - Caused by: java.lang.NullPointerException^M
2019-08-29 01:05:09 ERROR stderr:71 -   at org.apache.cxf.jaxrs.impl.MetadataMap.getMatchingKey(MetadataMap.java:162)^M
2019-08-29 01:05:09 ERROR stderr:71 -   at org.apache.cxf.jaxrs.impl.MetadataMap.remove(MetadataMap.java:200)^M
2019-08-29 01:05:09 ERROR stderr:71 -   at org.apache.cxf.jaxrs.impl.MetadataMap.remove(MetadataMap.java:35)^M
2019-08-29 01:05:09 ERROR stderr:71 -   at com.oracle.bmc.http.internal.ContentLengthFilter.filter(ContentLengthFilter.java:30)^M
2019-08-29 01:05:09 ERROR stderr:71 -   at org.apache.cxf.jaxrs.client.spec.ClientRequestFilterInterceptor.handleMessage(ClientRequestFilterInterceptor.java:71)^M
2019-08-29 01:05:09 ERROR stderr:71 -   at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)^M
2019-08-29 01:05:09 ERROR stderr:71 -   at org.apache.cxf.jaxrs.client.AbstractClient.doRunInterceptorChain(AbstractClient.java:710)^M
2019-08-29 01:05:09 ERROR stderr:71 -   at org.apache.cxf.jaxrs.client.WebClient.doChainedInvocation(WebClient.java:1051)^M
2019-08-29 01:05:09 ERROR stderr:71 -   ... 104 more^M


Null Pointer is coming from ContentLengthFilter line number 30: If there is no content-header present, then it is deleting null header. 
![ContentLengthFilter-NullPointer](https://user-images.githubusercontent.com/22631727/63902911-99630380-c9d9-11e9-9584-bb5985ab05db.PNG)

**Comment by andy-miles** [comment]
Instead of adding your own custom `ApacheConfigurator`, I recommend you leverage the Apache Connector Add-On: https://github.com/oracle/oci-java-sdk/tree/master/bmc-addons/bmc-apache-connector-provider

Example creating a new `ObjectStorageClient` instance:

```
ClientConfigurator configurator = new ApacheConfigurator();

ObjectStorageClient client = ObjectStorageClient.builder()
		.region(Region.US_PHOENIX_1)
		.clientConfigurator(configurator)
		.build(authenticationDetailsProvider);
```

After trying that, are you still seeing the `NullPointerException`?

**Comment by andy-miles** [comment]
@rsingareddy, please review my suggestion to use the vended `ApacheConfigurator` that is provided with the add-on to see if it addresses your `NullPointerException` issue.  If I don't hear back within the next few business days, I'll go ahead and close this issue.

**Comment by andy-miles** [comment]
Since there has been no reply, I'm closing this issue.  Please reopen if you have any further questions and/or concerns.
