### ISSUE TITLE
ListCompartmentsExample.java in examples started not to work

### ISSUE THREAD

**Issue by kyoukim** [oracle/oci-java-sdk#165]
I am trying to update the java-oci-sdk Oracle Linux RPMs. 

ListCompartmentsExample.java is inside the examples directory. It worked before, around the time that 1.5.9 was released. It does not seem to work now. 

Here's my .oci/config, and it seems sane to me:
```
[opc@kyoukim-instance-20191009-1534 examples]$ cat ~/.oci/config 
[DEFAULT]
user=ocid1.user.oc1..aaaaaaaaog6uoye4ote2nf72p7mjvhpjnlxpggij3e5xfhc5fzailor5gt5a
fingerprint=04:78:6e:69:d2:95:90:89:79:b7:00:d2:54:04:39:06
key_file=/home/opc/.oci/oci_api_key.pem
tenancy=ocid1.tenancy.oc1..aaaaaaaaojlj67jpdjvx7wszzrnwnooss3xxt66oldeyt2x35a6gthqdfr4q
region=us-ashburn-1
```

Actually, oci cli seems to work with that well:
```
[opc@kyoukim-instance-20191009-1534 examples]$ oci  iam compartment list > /dev/null 2>&1 || false
[opc@kyoukim-instance-20191009-1534 examples]$ echo $?
0
[opc@kyoukim-instance-20191009-1534 examples]$ oci  iam compartment list | wc -l
WARNING: This operation supports pagination and not all resources were returned.  Re-run using the --all option to auto paginate and list all resources.
305
```

I have built the .class file as follows:
```
[opc@kyoukim-instance-20191009-1534 examples]$ unset CLASSPATH
[opc@kyoukim-instance-20191009-1534 examples]$ pwd
/home/opc/oci-java-1.9.1/examples
[opc@kyoukim-instance-20191009-1534 examples]$ echo $CPATH3
/home/opc/oci-java-1.9.1/lib/oci-java-sdk-full-1.9.1.jar:/home/opc/oci-java-1.9.1/third-party/lib/*:/home/opc/oci-java-1.9.1/examples
[opc@kyoukim-instance-20191009-1534 examples]$ javac -cp $CPATH3 ListCompartmentsExample.java 
```

Running the example results in the following:
```
[opc@kyoukim-instance-20191009-1534 examples]$ java -cp $CPATH3 ListCompartmentsExample 
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" com.oracle.bmc.model.BmcException: (404, NotAuthorizedOrNotFound, false) Authorization failed or requested resource not found (opc-request-id: 6903265CD6D94F0EA2E3F5E8B90EB2D9/547D49E307903D3299F61CAD34D409DE/015FA7F54172C120B657D35ED7026116)
	at com.oracle.bmc.http.internal.ResponseHelper.throwIfNotSuccessful(ResponseHelper.java:137)
	at com.oracle.bmc.http.internal.ResponseConversionFunctionFactory$ValidatingParseResponseFunction.apply(ResponseConversionFunctionFactory.java:87)
	at com.oracle.bmc.http.internal.ResponseConversionFunctionFactory$ValidatingParseResponseFunction.apply(ResponseConversionFunctionFactory.java:83)
	at com.oracle.bmc.identity.internal.http.CreateCompartmentConverter$1.apply(CreateCompartmentConverter.java:65)
	at com.oracle.bmc.identity.internal.http.CreateCompartmentConverter$1.apply(CreateCompartmentConverter.java:50)
	at com.oracle.bmc.identity.IdentityClient.lambda$null$10(IdentityClient.java:566)
	at com.oracle.bmc.retrier.BmcGenericRetrier.lambda$execute$0(BmcGenericRetrier.java:50)
	at com.oracle.bmc.waiter.GenericWaiter.execute(GenericWaiter.java:54)
	at com.oracle.bmc.retrier.BmcGenericRetrier.execute(BmcGenericRetrier.java:46)
	at com.oracle.bmc.identity.IdentityClient.lambda$createCompartment$11(IdentityClient.java:558)
	at com.oracle.bmc.retrier.BmcGenericRetrier.lambda$execute$0(BmcGenericRetrier.java:50)
	at com.oracle.bmc.waiter.GenericWaiter.execute(GenericWaiter.java:54)
	at com.oracle.bmc.retrier.BmcGenericRetrier.execute(BmcGenericRetrier.java:46)
	at com.oracle.bmc.identity.IdentityClient.createCompartment(IdentityClient.java:552)
	at shared.ExampleCompartmentHelper.createCompartment(ExampleCompartmentHelper.java:36)
	at ListCompartmentsExample.main(ListCompartmentsExample.java:52)
```

The regression does not look like in examples themselves. Might it be caused by some changed in java-oci-sdk itself? Or, am I using a wrong config file from java-oci-sdk's perspective?

**Comment by jodoglevy** [comment]
Hi,

Looks like the create compartment call is failing for you. The NotAuthorizedOrNotFound error on a create probably means you are hitting a permissions issue.

Are you sure you are able to create compartments? It looks like you only tested that you can successfully _list_ compartments via the CLI, but not that you can _create_ them that way. If on the CLI you are also not able to create compartments, this means its a permissions issue with the user you are making the calls to OCI from the CLI / Java SDK as.

**Comment by kyoukim** [comment]
Sorry for the late reply. 

Indeed, creating a compartment with the tenancy in .oci/config did not work. 

However, I got a few more questions. I belong to a compartment, which belongs to the root compartment. What should be my "tenancy" in my ~/.oci/config? I believed that it should be the root compartment. If so, there must be still things that do not work.

```
[opc@kyoukim-instance-20191029-1639 examples]$ export MY_COMP_ID=ocid1.compartment.oc1..aaaaaaaaqxtejeokn6loadjp5d4l5bbapsflqmvr2msjxv2a2lhyqlzshtta
[opc@kyoukim-instance-20191029-1639 examples]$ export ROOT_COMP_ID=ocid1.tenancy.oc1..aaaaaaaaojlj67jpdjvx7wszzrnwnooss3xxt66oldeyt2x35a6gthqdfr4q
[opc@kyoukim-instance-20191029-1639 examples]$ oci iam compartment create -c $ROOT_COMP_ID --name "CP-11" --description "testing what java-oci-jdk does by creating CP-11 instead of CP-1" > /dev/null
ServiceError:
{
    "code": "NotAuthorizedOrNotFound", 
    "message": "Authorization failed or requested resource not found", 
    "opc-request-id": "18C1B236FB8848D6BCD29BD50B01D0EA/54EE9B974A01D730C8D38C10BD632922/7E2F44617787492A59957279FD47C01A", 
    "status": 404
}
[opc@kyoukim-instance-20191029-1639 examples]$ oci iam compartment create -c $MY_COMP_ID --name "CP-13" --description "testing what java-oci-jdk does by creating CP-11 instead of CP-1" > /dev/null
[opc@kyoukim-instance-20191029-1639 examples]$ echo $?
0
[opc@kyoukim-instance-20191029-1639 examples]$ egrep $MY_COMP_ID ~/.oci/config
[opc@kyoukim-instance-20191029-1639 examples]$ echo $?
1
[opc@kyoukim-instance-20191029-1639 examples]$ egrep $ROOT_COMP_ID ~/.oci/config > /dev/null
[opc@kyoukim-instance-20191029-1639 examples]$ echo $?
0
```

I believe the ListCompartmentExamples.java picks up the tenancy in .oci/config, so effectively, the root compartment id is picked up. It does not work. If I change the value of "tenancy" in config, I got this:

```
[opc@kyoukim-instance-20191029-1639 examples]$ javac -cp $CLASSPATH:$PWD ListCompartmentsExample.java
[opc@kyoukim-instance-20191029-1639 examples]$ java -cp $CLASSPATH:$PWD ListCompartmentsExample
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" com.oracle.bmc.model.BmcException: (401, NotAuthenticated, false) The required information to complete authentication was not provided or was incorrect. (opc-request-id: 29D38A3681934F52B751861B7880EB14/BA5E59A15A042A51A9B298C20AA2EDEA/C99FEF362BBB09CC13E2C88BACE604F8)
	at com.oracle.bmc.http.internal.ResponseHelper.throwIfNotSuccessful(ResponseHelper.java:127)
	at com.oracle.bmc.http.internal.ResponseConversionFunctionFactory$ValidatingParseResponseFunction.apply(ResponseConversionFunctionFactory.java:86)
	at com.oracle.bmc.http.internal.ResponseConversionFunctionFactory$ValidatingParseResponseFunction.apply(ResponseConversionFunctionFactory.java:82)
	at com.oracle.bmc.identity.internal.http.CreateCompartmentConverter$1.apply(CreateCompartmentConverter.java:65)
	at com.oracle.bmc.identity.internal.http.CreateCompartmentConverter$1.apply(CreateCompartmentConverter.java:50)
	at com.oracle.bmc.identity.IdentityClient.lambda$null$8(IdentityClient.java:537)
	at com.oracle.bmc.retrier.BmcGenericRetrier.lambda$execute$0(BmcGenericRetrier.java:50)
	at com.oracle.bmc.waiter.GenericWaiter.execute(GenericWaiter.java:54)
	at com.oracle.bmc.retrier.BmcGenericRetrier.execute(BmcGenericRetrier.java:46)
	at com.oracle.bmc.identity.IdentityClient.lambda$createCompartment$9(IdentityClient.java:529)
	at com.oracle.bmc.retrier.BmcGenericRetrier.lambda$execute$0(BmcGenericRetrier.java:50)
	at com.oracle.bmc.waiter.GenericWaiter.execute(GenericWaiter.java:54)
	at com.oracle.bmc.retrier.BmcGenericRetrier.execute(BmcGenericRetrier.java:46)
	at com.oracle.bmc.identity.IdentityClient.createCompartment(IdentityClient.java:523)
	at ListCompartmentsExample.createCompartment(ListCompartmentsExample.java:155)
	at ListCompartmentsExample.main(ListCompartmentsExample.java:52)
```

I think, with the changed compartment id, I could create a compartment from the commandline.

**Comment by jodoglevy** [comment]
>  I belong to a compartment, which belongs to the root compartment. What should be my "tenancy" in my ~/.oci/config? I believed that it should be the root compartment.

Correct, it should be root compartment - this is the same as tenancy.

> I think, with the changed compartment id, I could create a compartment from the commandline.

I don't think so, presumably you'd get the same error about authentication failing ('NotAuthenticated') from the CLI -- authN cannot be completed, regardless of the tool you use, if you do not put the tenancy id into the config file in the "tenancy" field.

The tenancy id should be put in the config file in the "tenancy" field. Then authentication will work for you. In terms of the 'NotAuthorizedOrNotFound' error, which is a check that comes **after** authentication completes, I believe that is a permissions issue, where the user you are trying to create compartments as (regardless of tool used to do so - SDK, CLI, console), does not have permissions to do so. If you resolve the permissions issues for this user, I think things will work.

**Comment by kyoukim** [comment]
Perhaps, then, the oci commanline tool works differently from what is expected. Please, read the list of commands in my posting. "oci iam compartment create" seems to take a "-c" option. Via the option, I gave my compartment id (toolchain) rather than the root compartment id(tenancy in my config file), osdevelopment. It seemed to work. 

However, when I gave the root compartment id via "-c" option, it did not work.

While I am doing this, the "config" file had the root compartment id as the value of the "tenancy" key. The most frequent use case of my OCI instance is running a "packer" utility to build a custom image from a json file. Thus, I do believe that it is likely my "config" has been sane. Otherwise, I must have gotten errors when I created my custom OCI images. 

Your comments made me believe two things:
 1. I have to double-check with someone who gives me permissions
 2. oci commandline utility does not work as it is expected if java-oci-sdk is working correctly and as expected

Thank you!

**Comment by jodoglevy** [comment]
Sounds like you have the permissions to create compartments within your compartment, but not within the root compartment (tenancy). In that case, you will need to modify ListCompartmentsExample for your own needs, so that it creates compartments within a compartment that you have access to create compartments within. The example, as written, creates compartments within the root compartment. This does not work for you due to the limited permissions of the user you are using when running the example.

That or have the permissions for this user expanded to include creating compartments within the root compartment. Either should work.

**Comment by jodoglevy** [comment]
@kyoukim  are you still hitting an issue here? Can this be closed?

**Comment by kyoukim** [comment]
I think it could be closed. Thank you!
