### ISSUE TITLE
javax.ws.rs.ProcessingException: RESTEASY003215: could not find writer for content-type application/json type: java.lang.Strin

### ISSUE THREAD

**Issue by sankaradabala** [oracle/oci-java-sdk#172]
While executing  the following code using the example in monitoring project we are seeing the  Caused by: javax.ws.rs.ProcessingException: RESTEASY003215: could not find writer for content-type application/json type: java.lang.String

Sample code
 public static void main(String[] args) throws Exception {
        if (args.length < 1) {
            printUsageAndThrowException("Insufficient args\n");
        }

        final String compartment = args[0];
        final String namespace = args.length > 1 ? args[1] : null;
        final String metricName = args.length > 2 ? args[2] : null;
        
        try (MonitoringClient monitoringClient = getMonitoringClient(CONFIG_PROFILE_DEFAULT)) {
            final ListMetricsRequest request =
                    ListMetricsRequest.builder()
                            .compartmentId(compartment)
                            .listMetricsDetails(
                                    ListMetricsDetails.builder()
                                            .namespace(namespace)
                                            .name(metricName)
                                            .build())
                            .build();

            System.out.printf("Request constructed:\n%s\n\n", request.getListMetricsDetails());

            System.out.println("Sending...");
            ListMetricsResponse response = monitoringClient.listMetrics(request);

            System.out.printf(
                    "\n\nReceived response [opc-request-id: %s]\n", response.getOpcRequestId());
            System.out.printf("%s\n\n", response.getItems());
        }

Exception stacktrace.
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Request constructed:
ListMetricsDetails(name=CpuUtilization, namespace=oci_computeagent, resourceGroup=null, dimensionFilters=null, groupBy=null, sortBy=null, sortOrder=null, __explicitlySet__=[namespace, name])

Sending...
Exception in thread "main" com.oracle.bmc.model.BmcException: (-1, null, false) Processing exception while communicating to: https://telemetry.us-phoenix-1.oraclecloud.com (outbound opc-request-id: C2D724C781FC4316AD3944CC7639CF52)
	at com.oracle.bmc.http.internal.RestClient.convertToBmcException(RestClient.java:578)
	at com.oracle.bmc.http.internal.RestClient.post(RestClient.java:156)
	at com.oracle.bmc.monitoring.MonitoringClient.lambda$null$14(MonitoringClient.java:606)
	at com.oracle.bmc.retrier.BmcGenericRetrier.lambda$execute$0(BmcGenericRetrier.java:50)
	at com.oracle.bmc.waiter.GenericWaiter.execute(GenericWaiter.java:54)
	at com.oracle.bmc.retrier.BmcGenericRetrier.execute(BmcGenericRetrier.java:46)
	at com.oracle.bmc.monitoring.MonitoringClient.lambda$listMetrics$15(MonitoringClient.java:602)
	at com.oracle.bmc.retrier.BmcGenericRetrier.lambda$execute$0(BmcGenericRetrier.java:50)
	at com.oracle.bmc.waiter.GenericWaiter.execute(GenericWaiter.java:54)
	at com.oracle.bmc.retrier.BmcGenericRetrier.execute(BmcGenericRetrier.java:46)
	at com.oracle.bmc.monitoring.MonitoringClient.listMetrics(MonitoringClient.java:596)
	at ocihostmonitoring.HostMetrics.main(HostMetrics.java:54)
Caused by: javax.ws.rs.ProcessingException: RESTEASY004655: Unable to invoke request
	at org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient4Engine.invoke(ApacheHttpClient4Engine.java:321)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:439)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:61)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocationBuilder.post(ClientInvocationBuilder.java:219)
	at com.oracle.bmc.http.internal.ForwardingInvocationBuilder.post(ForwardingInvocationBuilder.java:156)
	at com.oracle.bmc.http.internal.RestClient.post(RestClient.java:153)
	... 10 more
Caused by: javax.ws.rs.ProcessingException: RESTEASY003215: could not find writer for content-type application/json type: java.lang.String
	at org.jboss.resteasy.core.interception.ClientWriterInterceptorContext.throwWriterNotFoundException(ClientWriterInterceptorContext.java:38)
	at org.jboss.resteasy.core.interception.AbstractWriterInterceptorContext.getWriter(AbstractWriterInterceptorContext.java:146)
	at org.jboss.resteasy.core.interception.AbstractWriterInterceptorContext.proceed(AbstractWriterInterceptorContext.java:121)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.writeRequestBody(ClientInvocation.java:394)
	at org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient4Engine.writeRequestBodyToOutputStream(ApacheHttpClient4Engine.java:666)
	at org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient4Engine.buildEntity(ApacheHttpClient4Engine.java:631)
	at org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient4Engine.loadHttpMethod(ApacheHttpClient4Engine.java:509)
	at org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient4Engine.invoke(ApacheHttpClient4Engine.java:310)
	... 15 more

**Comment by andy-miles** [comment]
It looks like you are using both Apach and RestEasy Jersey connector providers in your classpath.  Which Jersey implementation are you wanting to use?  If you just want to use the default HttpUrlConnectorProvider, I recommend to remove any references to the rest easy and apache connector providers from your classpath.

If you specifically want to use RESTEasy or Apache, then you'll want to just reference one of the add-ons in your application's classpath along with the corresponding dependencies for the associated connector provider.

**Comment by sankaradabala** [comment]
Thanks, This got resolved after commenting out the following which is brining resteasy dependency

**Comment by rohit-s8** [comment]
Having the same problem and unfortunately didn't really follow the conversation above. @andy-miles can you mention which dependencies specifically need to be excluded in both the cases you mentioned?

**Comment by jeanabraham** [comment]
@rohit-s8 I'm running into the same issue with Quarkus rest-client. Were you able to figure out the solution? Thanks!

**Comment by rohit-s8** [comment]
yes @jeanabraham I was able to figure out in the end. You just need to use a custom ClientConfigurator while building/configuring the client (see here: https://github.com/oracle/oci-java-sdk/blob/07e02628a99e09fb354fc442a34d4b450c5e7a47/bmc-addons/bmc-resteasy-client-configurator/src/main/java/com/oracle/bmc/http/ResteasyClientConfigurator.java#L15)

The above is available as a separate package, or just use it as a reference to implement your own (it's just this one class that you need). And then you build your client in your producer as below:

```java
@Produces
@RequestScoped
public ObjectStorageClient objectStorageClient(ConfigFileAuthenticationDetailsProvider provider) {
  return ObjectStorageClient.builder()
    .additionalClientConfigurator(new ResteasyClientConfigurator())
    .build(provider);
}
```

**Comment by jsymon** [comment]
> yes @jeanabraham I was able to figure out in the end. You just need to use a custom ClientConfigurator while building/configuring the client (see here:
> 
> https://github.com/oracle/oci-java-sdk/blob/07e02628a99e09fb354fc442a34d4b450c5e7a47/bmc-addons/bmc-resteasy-client-configurator/src/main/java/com/oracle/bmc/http/ResteasyClientConfigurator.java#L15
> 
> )
> The above is available as a separate package, or just use it as a reference to implement your own (it's just this one class that you need). And then you build your client in your producer as below:
> 
> ```java
> @Produces
> @RequestScoped
> public ObjectStorageClient objectStorageClient(ConfigFileAuthenticationDetailsProvider provider) {
>   return ObjectStorageClient.builder()
>     .additionalClientConfigurator(new ResteasyClientConfigurator())
>     .build(provider);
> }
> ```

For reference, I was having a similar problem with `ComputeClient`. 
Modifying the constructor with the additional parameters fixed the issue:

        List<ClientConfigurator> configurators = Arrays.asList(new ResteasyClientConfigurator());
        client = new ComputeClient(provider,
                null,
                null,
                new DefaultRequestSignerFactory(SigningStrategy.STANDARD),
                configurators);
