### ISSUE TITLE
Unrecognized field "emailVerified" (class com.oracle.bmc.identity.model.User$Builder)

### ISSUE THREAD

**Issue by anilyv** [oracle/oci-java-sdk#217]
I am hitting the below error with oci-java-sdk-1.17.0:

<May 7, 2020 2:48:15,357 PM UTC> <Error> <oracle.bi.security.identity> <BEA-000000> <Unable to get user profile: Error reading entity from input stream.>
javax.ws.rs.ProcessingException: Error reading entity from input stream.
        at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:889)
        at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:808)
        at org.glassfish.jersey.client.ClientResponse.readEntity(ClientResponse.java:326)
        at org.glassfish.jersey.client.InboundJaxrsResponse$1.call(InboundJaxrsResponse.java:115)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:419)
        at org.glassfish.jersey.client.InboundJaxrsResponse.runInScopeIfPossible(InboundJaxrsResponse.java:267)
        at org.glassfish.jersey.client.InboundJaxrsResponse.readEntity(InboundJaxrsResponse.java:112)
        at com.oracle.bmc.http.internal.ResponseHelper.readEntity(ResponseHelper.java:232)
        at com.oracle.bmc.http.internal.ResponseConversionFunctionFactory$ParseResponseWithHeadersFunction.doApply(ResponseConversionFunctionFactory.java:57)
        at com.oracle.bmc.http.internal.ResponseConversionFunctionFactory$ParseResponseWithHeadersFunction.doApply(ResponseConversionFunctionFactory.java:50)
        at com.oracle.bmc.http.internal.ResponseConversionFunctionFactory$ValidatingParseResponseFunction.apply(ResponseConversionFunctionFactory.java:87)
        at com.oracle.bmc.http.internal.ResponseConversionFunctionFactory$ValidatingParseResponseFunction.apply(ResponseConversionFunctionFactory.java:82)
        at com.oracle.bmc.identity.internal.http.GetUserConverter$1.apply(GetUserConverter.java:68)
        at com.oracle.bmc.identity.internal.http.GetUserConverter$1.apply(GetUserConverter.java:56)
        at com.oracle.bmc.identity.IdentityClient.lambda$null$112(IdentityClient.java:2124)
        at com.oracle.bmc.retrier.BmcGenericRetrier.lambda$execute$0(BmcGenericRetrier.java:50)
        at com.oracle.bmc.waiter.GenericWaiter.execute(GenericWaiter.java:54)
        at com.oracle.bmc.retrier.BmcGenericRetrier.execute(BmcGenericRetrier.java:46)
        at com.oracle.bmc.identity.IdentityClient.lambda$getUser$113(IdentityClient.java:2120)
        at com.oracle.bmc.retrier.BmcGenericRetrier.lambda$execute$0(BmcGenericRetrier.java:50)
        at com.oracle.bmc.waiter.GenericWaiter.execute(GenericWaiter.java:54)
        at com.oracle.bmc.retrier.BmcGenericRetrier.execute(BmcGenericRetrier.java:46)
        at com.oracle.bmc.identity.IdentityClient.getUser(IdentityClient.java:2114)
        at oracle.bi.security.identity.UPIIdentityStore.getUser(UPIIdentityStore.java:719)
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "emailVerified" (class com.oracle.bmc.identity.model.User$Builder), not marked as ignorable (14 known properties: "definedTags", "lifecycleState", "freeformTags", "identityProviderId", "name", "compartmentId", "isMfaActivated", "externalIdentifier", "capabilities", "id", "description", "inactiveStatus", "timeCreated", "email"])
 at [Source: org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream@12d0402d; line: 10, column: 26] (through reference chain: com.oracle.bmc.identity.model.Builder["emailVerified"])
        at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:62)
        at com.fasterxml.jackson.databind.DeserializationContext.reportUnknownProperty(DeserializationContext.java:851)
        at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1085)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1392)

**Comment by anilyv** [comment]
We have multiple versions of jackson libraries loaded in the jvm. After removing all others except the ones under third-party/lib, the issue got resolved.
