### ISSUE TITLE
SDK no longer works with Java 11+

### ISSUE THREAD

**Issue by recursivecodes** [oracle/oci-java-sdk#220]
When trying a simple use case with the OCI SDK and running under Oracle JDK 11+, the application fails with

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" com.oracle.bmc.http.signing.internal.PEMFileRSAPrivateKeySupplier$PEMFileRSAPrivateKeySupplierException: org.bouncycastle.openssl.PEMException: exception processing key pair: JCE cannot authenticate the provider BC
        at com.oracle.bmc.http.signing.internal.PEMFileRSAPrivateKeySupplier.<init>(PEMFileRSAPrivateKeySupplier.java:120)
        at com.oracle.bmc.http.signing.internal.DefaultRequestSignerFactory.createKeySupplier(DefaultRequestSignerFactory.java:111)
        at com.oracle.bmc.http.signing.internal.DefaultRequestSignerFactory.createRequestSigner(DefaultRequestSignerFactory.java:54)
        at com.oracle.bmc.objectstorage.ObjectStorageClient.<init>(ObjectStorageClient.java:268)
        at com.oracle.bmc.objectstorage.ObjectStorageClient.<init>(ObjectStorageClient.java:217)
        at com.oracle.bmc.objectstorage.ObjectStorageClient.<init>(ObjectStorageClient.java:180)
        at com.oracle.bmc.objectstorage.ObjectStorageClient.<init>(ObjectStorageClient.java:145)
        at com.oracle.bmc.objectstorage.ObjectStorageClient.<init>(ObjectStorageClient.java:117)
        at com.oracle.bmc.objectstorage.ObjectStorageClient.<init>(ObjectStorageClient.java:92)
        at com.oracle.bmc.objectstorage.ObjectStorageClient.<init>(ObjectStorageClient.java:69)
        at com.oracle.bmc.objectstorage.ObjectStorageClient.<init>(ObjectStorageClient.java:55)
        at com.oracle.bmc.objectstorage.ObjectStorageClient.<init>(ObjectStorageClient.java:44)
        at codes.recursive.Test.main(Test.java:22)
Caused by: org.bouncycastle.openssl.PEMException: exception processing key pair: JCE cannot authenticate the provider BC
        at org.bouncycastle.openssl.PEMEncryptedKeyPair.decryptKeyPair(Unknown Source)
        at com.oracle.bmc.http.signing.internal.PEMFileRSAPrivateKeySupplier.<init>(PEMFileRSAPrivateKeySupplier.java:94)
        ... 12 more
Caused by: java.lang.SecurityException: JCE cannot authenticate the provider BC
        at java.base/javax.crypto.JceSecurity.getInstance(JceSecurity.java:145)
        at java.base/javax.crypto.SecretKeyFactory.getInstance(SecretKeyFactory.java:252)
        at org.bouncycastle.jcajce.util.ProviderJcaJceHelper.createSecretKeyFactory(Unknown Source)
        at org.bouncycastle.openssl.jcajce.PEMUtilities.getKey(Unknown Source)
        at org.bouncycastle.openssl.jcajce.PEMUtilities.getKey(Unknown Source)
        at org.bouncycastle.openssl.jcajce.PEMUtilities.crypt(Unknown Source)
        at org.bouncycastle.openssl.jcajce.JcePEMDecryptorProviderBuilder$1$1.decrypt(Unknown Source)
        ... 14 more
Caused by: java.util.jar.JarException: file:/Users/trsharp/Projects/sdk/oci-java-sdk-demo/build/libs/oci-java-sdk-demo-1.0-SNAPSHOT-all.jar has unsigned entries - codes/recursive/Test.class
        at java.base/javax.crypto.JarVerifier.verifySingleJar(JarVerifier.java:459)
        at java.base/javax.crypto.JarVerifier.verifyJars(JarVerifier.java:314)
        at java.base/javax.crypto.JarVerifier.verify(JarVerifier.java:257)
        at java.base/javax.crypto.ProviderVerifier.verify(ProviderVerifier.java:129)
        at java.base/javax.crypto.JceSecurity.verifyProvider(JceSecurity.java:191)
        at java.base/javax.crypto.JceSecurity.getVerificationResult(JceSecurity.java:217)
        at java.base/javax.crypto.JceSecurity.getInstance(JceSecurity.java:141)
        ... 20 more

```

See repro case:

https://github.com/recursivecodes/oci-java-sdk-demo

This example works as expected under other JDKs on 11+ - the issue only exists under Oracle JDK.

**Comment by mricken** [comment]
Hi @recursivecodes , I'm sorry I got pulled away, I was able to reproduce this locally, and am working on a mitigation.

**Comment by recursivecodes** [comment]
Any update @mricken?

**Comment by carimura** [comment]
Hi all -- Chad from the Java team here. If this still exists for our customers, it's a pretty bad look. Can we prioritize this issue to get it resolved?

**Comment by jodoglevy** [comment]
Hi @carimura @recursivecodes  - let me sync up with @mricken on this and get back to you next week

**Comment by carimura** [comment]
Also ++@calnan!

**Comment by recursivecodes** [comment]
Just a note, because I keep forgetting- the bug is demonstrated in the `demo-bug` branch of the repo above.

**Comment by priteshkp** [comment]
May not fix the problem, but I think one thing that needs to be done is to update the version of BC being used, per BC:

```
Further Note (users of Oracle JVM 1.7 or earlier, users of "pre-Java 9" toolkits): As of 1.63 we have started including signed jars for "jdk15to18", if you run into issues with either signature validation in the JCE or the presence of the multi-release versions directory in the regular "jdk15on" jar files try the "jdk15to18" jars instead. Please also note the JCE certificate in the public access versions of Oracle Java 6 (6u45) and Oracle Java 7 (7u80) is expiring on the 20th April this year (2020). Oracle does distribute JVMs for Java 6 and Java 7 with a newer, and stronger, certificate to holders of Java Support Contracts.
``` 

We currently use 1.60 jdk15on:
https://github.com/oracle/oci-java-sdk/blob/bafb1044d5881e59f6ef103ad88d1199ddd99976/bmc-common/pom.xml#L75
https://github.com/oracle/oci-java-sdk/blob/bafb1044d5881e59f6ef103ad88d1199ddd99976/bmc-common/pom.xml#L17

**Comment by recursivecodes** [comment]
CC @graemerocher because I think this may be the same issue we were seeing with native image.

**Comment by mricken** [comment]
@recursivecodes I'm back looking at this. I'm building and running this under Java 11, but cannot reproduce it.

I checked out the `demo-bug` of https://github.com/recursivecodes/oci-java-sdk-demo/tree/demo-bug

```
$ git remote -v
origin	https://github.com/recursivecodes/oci-java-sdk-demo.git (fetch)
origin	https://github.com/recursivecodes/oci-java-sdk-demo.git (push)
(540) 15:18:57 - [demo-bug ?] mricken@mricken-Mac
~/Documents/Projects/oncall/github-java-220/oci-java-sdk-demo
$ git branch -al
* demo-bug
  master
  remotes/origin/HEAD -> origin/master
  remotes/origin/demo-bug
  remotes/origin/master
(541) 15:19:08 - [demo-bug ?] mricken@mricken-Mac
~/Documents/Projects/oncall/github-java-220/oci-java-sdk-demo
$ git pull
Already up-to-date.
(542) 15:19:15 - [demo-bug ?] mricken@mricken-Mac
~/Documents/Projects/oncall/github-java-220/oci-java-sdk-demo
$ git status
On branch demo-bug
Your branch is up-to-date with 'origin/demo-bug'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	.java-version

nothing added to commit but untracked files present (use "git add" to track)
(546) 15:23:47 - [demo-bug ?] mricken@mricken-Mac
~/Documents/Projects/oncall/github-java-220/oci-java-sdk-demo
```

I'm using `jenv` to locally set Java 11. Could that be the problem?

```
$ jenv version
oracle64-11.0.7 (set by /Users/mricken/Documents/Projects/oncall/github-java-220/oci-java-sdk-demo/.java-version)
(543) 15:19:29 - [demo-bug ?] mricken@mricken-Mac
~/Documents/Projects/oncall/github-java-220/oci-java-sdk-demo
$ java -version
java version "11.0.7" 2020-04-14 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.7+8-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.7+8-LTS, mixed mode)
```

I build and run it, without getting an error:

```
$ ./gradlew assemble && java -jar build/libs/oci-java-sdk-demo-1.0-SNAPSHOT-all.jar

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 10s
9 actionable tasks: 8 executed, 1 up-to-date
<-------------> 0% WAITING
> IDLE
done
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Getting the namespace.
dex-us-phoenix-1-manual
(545) 15:20:22 - [demo-bug ?] mricken@mricken-Mac
~/Documents/Projects/oncall/github-java-220/oci-java-sdk-demo
```

Any idea why I'm unable to reproduce the problem?

**Comment by mricken** [comment]
It is executing under Java 11 for me:

```
~/Documents/Projects/oncall/github-java-220/oci-java-sdk-demo
$ ./gradlew assemble && java -jar build/libs/oci-java-sdk-demo-1.0-SNAPSHOT-all.jar

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 32s
9 actionable tasks: 8 executed, 1 up-to-date
11.0.7
done
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Getting the namespace.
dex-us-phoenix-1-manual
(563) 15:41:06 - [demo-bug !?] mricken@mricken-Mac
~/Documents/Projects/oncall/github-java-220/oci-java-sdk-demo
$ git diff
diff --git a/src/main/java/codes/recursive/Test.java b/src/main/java/codes/recursive/Test.java
index 51a649f..bbbfe98 100644
--- a/src/main/java/codes/recursive/Test.java
+++ b/src/main/java/codes/recursive/Test.java
@@ -12,6 +12,8 @@ import java.io.IOException;

 public class Test {
     public static void main(String[] args) throws IOException {
+        System.out.println(System.getProperty("java.version"));
+
         String configurationFilePath = "~/.oci/config";
         String profile = "DEFAULT";
         System.out.println("done");
(564) 15:41:39 - [demo-bug !?] mricken@mricken-Mac
~/Documents/Projects/oncall/github-java-220/oci-java-sdk-demo
```

**Comment by recursivecodes** [comment]
Make sure you're using a profile that has a private key encrypted with a passphrase. The issue will not manifest without that.

**Comment by mricken** [comment]
With passphrase, I am able to reproduce. Thank you, @recursivecodes .

```
11.0.7
done
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" com.oracle.bmc.http.signing.internal.PEMFileRSAPrivateKeySupplier$PEMFileRSAPrivateKeySupplierException: org.bouncycastle.openssl.PEMException: exception processing key pair: JCE cannot authenticate the provider BC
	at com.oracle.bmc.http.signing.internal.PEMFileRSAPrivateKeySupplier.<init>(PEMFileRSAPrivateKeySupplier.java:120)
	at com.oracle.bmc.http.signing.internal.DefaultRequestSignerFactory.createKeySupplier(DefaultRequestSignerFactory.java:111)
	at com.oracle.bmc.http.signing.internal.DefaultRequestSignerFactory.createRequestSigner(DefaultRequestSignerFactory.java:54)
	at com.oracle.bmc.objectstorage.ObjectStorageClient.<init>(ObjectStorageClient.java:268)
	at com.oracle.bmc.objectstorage.ObjectStorageClient.<init>(ObjectStorageClient.java:217)
	at com.oracle.bmc.objectstorage.ObjectStorageClient.<init>(ObjectStorageClient.java:180)
	at com.oracle.bmc.objectstorage.ObjectStorageClient.<init>(ObjectStorageClient.java:145)
	at com.oracle.bmc.objectstorage.ObjectStorageClient.<init>(ObjectStorageClient.java:117)
	at com.oracle.bmc.objectstorage.ObjectStorageClient.<init>(ObjectStorageClient.java:92)
	at com.oracle.bmc.objectstorage.ObjectStorageClient.<init>(ObjectStorageClient.java:69)
	at com.oracle.bmc.objectstorage.ObjectStorageClient.<init>(ObjectStorageClient.java:55)
	at com.oracle.bmc.objectstorage.ObjectStorageClient.<init>(ObjectStorageClient.java:44)
	at codes.recursive.Test.main(Test.java:27)
Caused by: org.bouncycastle.openssl.PEMException: exception processing key pair: JCE cannot authenticate the provider BC
	at org.bouncycastle.openssl.PEMEncryptedKeyPair.decryptKeyPair(Unknown Source)
	at com.oracle.bmc.http.signing.internal.PEMFileRSAPrivateKeySupplier.<init>(PEMFileRSAPrivateKeySupplier.java:94)
	... 12 more
Caused by: java.lang.SecurityException: JCE cannot authenticate the provider BC
	at java.base/javax.crypto.JceSecurity.getInstance(JceSecurity.java:145)
	at java.base/javax.crypto.SecretKeyFactory.getInstance(SecretKeyFactory.java:252)
	at org.bouncycastle.jcajce.util.ProviderJcaJceHelper.createSecretKeyFactory(Unknown Source)
	at org.bouncycastle.openssl.jcajce.PEMUtilities.getKey(Unknown Source)
	at org.bouncycastle.openssl.jcajce.PEMUtilities.getKey(Unknown Source)
	at org.bouncycastle.openssl.jcajce.PEMUtilities.crypt(Unknown Source)
	at org.bouncycastle.openssl.jcajce.JcePEMDecryptorProviderBuilder$1$1.decrypt(Unknown Source)
	... 14 more
Caused by: java.util.jar.JarException: file:/Users/mricken/Documents/Projects/oncall/github-java-220/oci-java-sdk-demo/build/libs/oci-java-sdk-demo-1.0-SNAPSHOT-all.jar has unsigned entries - codes/recursive/Test.class
	at java.base/javax.crypto.JarVerifier.verifySingleJar(JarVerifier.java:459)
	at java.base/javax.crypto.JarVerifier.verifyJars(JarVerifier.java:314)
	at java.base/javax.crypto.JarVerifier.verify(JarVerifier.java:257)
	at java.base/javax.crypto.ProviderVerifier.verify(ProviderVerifier.java:129)
	at java.base/javax.crypto.JceSecurity.verifyProvider(JceSecurity.java:191)
	at java.base/javax.crypto.JceSecurity.getVerificationResult(JceSecurity.java:217)
	at java.base/javax.crypto.JceSecurity.getInstance(JceSecurity.java:141)
	... 20 more
```

**Comment by recursivecodes** [comment]
The JDK team has determined that this issue is not a bug. I will continue to use BC as a shadow dependency when deploying to Oracle JVMs.

**Comment by mricken** [comment]
It seems like this was an issue with the way the `oci-java-sdk-demo-1.0-SNAPSHOT-all.jar` was constructed.
