### ISSUE TITLE
AbstractMethodError: com.oracle.bmc.http.ApacheConfigurator.customizeBuilder(Lshaded/com/oracle/oci/javasdk/javax/ws/rs/client/ClientBuilder;)V

### ISSUE THREAD

**Issue by vikash-oracle** [oracle/oci-java-sdk#227]
Attempted to configure an ObjectStorage client to connect through an unauthenticated HTTP proxy using ApacheConfigurator, but failed with error _**AbstractMethodError: com.oracle.bmc.http.ApacheConfigurator.customizeBuilder(Lshaded/com/oracle/oci/javasdk/javax/ws/rs/client/ClientBuilder;)V**_

Libs used:
shaded/lib/oci-java-sdk-full-shaded-1.17.5.jar
addons/apache-connector/lib/oci-java-sdk-addons-apache-1.17.5.jar 

Exception in thread "main"
java.lang.AbstractMethodError: com.oracle.bmc.http.ApacheConfigurator.customizeBuilder(Lshaded/com/oracle/oci/javasdk/javax/ws/rs/client/ClientBuilder;)V
    at com.oracle.bmc.http.CompositeClientConfigurator.customizeBuilder(CompositeClientConfigurator.java:41)
    at com.oracle.bmc.http.internal.RestClientFactory.createClient(RestClientFactory.java:167)
    at com.oracle.bmc.http.internal.RestClientFactory.create(RestClientFactory.java:146)
    at com.oracle.bmc.objectstorage.ObjectStorageClient.<init>(ObjectStorageClient.java:292)
    at com.oracle.bmc.objectstorage.ObjectStorageClient.<init>(ObjectStorageClient.java:217)
    at com.oracle.bmc.objectstorage.ObjectStorageClient$Builder.build(ObjectStorageClient.java:377)

**Comment by vikash-oracle** [comment]
I referred to example https://github.com/oracle/oci-java-sdk/blob/master/bmc-examples/src/main/java/HttpProxyExample.java

**Comment by vikash-oracle** [comment]
Can the apache addons be shaded and bundled with oci-java-sdk-full-shaded-1.17.5.jar?

**Comment by omkar07** [comment]
Hi Vikash, As discussed yesterday closing this issue and as suggested by @mricken "you can create a shaded jar and include it". Please feel to reopen the issue incase you need additional info.
