### ISSUE TITLE
Object Storage SDK does not work with JBoss RESTEASY HttpClient

### ISSUE THREAD

**Issue by praburajan** [oracle/oci-java-sdk#240]
I am from the Oracle Integration - Process Cloud team. We had to switch from Confluent Schema Registry to Apicurio Schema Registry for our product's Kafka schema registry requirements due to licensing issues.

When Apicurio schema registry client is included in the runtime classpath, it somehow takes precedence and Object storage SDK tries to use the RESTEASY's implementation of jaxrs Invocation.Builder and fails with the following error. I am not able to figure out why Object storage sdk fails to work with RESTEASY http client.

```
Caused by:
        javax.ws.rs.ProcessingException: RESTEASY004655: Unable to invoke request: javax.ws.rs.ProcessingException: RESTEASY003215: could not find writer for content-type application/octet-stream type: com.oracle.bmc.io.internal.KeepOpenInputStream
            at org.jboss.resteasy.client.jaxrs.engines.ManualClosingApacheHttpClient43Engine.invoke(ManualClosingApacheHttpClient43Engine.java:286)
            at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:488)
            at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:65)
            at org.jboss.resteasy.client.jaxrs.internal.ClientInvocationBuilder.put(ClientInvocationBuilder.java:208)
            at com.oracle.bmc.http.internal.ForwardingInvocationBuilder.put(ForwardingInvocationBuilder.java:142)
            at com.oracle.bmc.http.internal.RestClient.lambda$put$9(RestClient.java:448)
            at com.oracle.bmc.http.internal.RestClient.put(RestClient.java:448)
            ... 12 more
            Caused by:
            javax.ws.rs.ProcessingException: RESTEASY003215: could not find writer for content-type application/octet-stream type: com.oracle.bmc.io.internal.KeepOpenInputStream
                at org.jboss.resteasy.core.interception.jaxrs.ClientWriterInterceptorContext.throwWriterNotFoundException(ClientWriterInterceptorContext.java:50)
                at org.jboss.resteasy.core.interception.jaxrs.AbstractWriterInterceptorContext.getWriter(AbstractWriterInterceptorContext.java:302)
                at org.jboss.resteasy.core.interception.jaxrs.AbstractWriterInterceptorContext.syncProceed(AbstractWriterInterceptorContext.java:240)
                at org.jboss.resteasy.core.interception.jaxrs.AbstractWriterInterceptorContext.proceed(AbstractWriterInterceptorContext.java:224)
                at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.writeRequestBody(ClientInvocation.java:440)
                at org.jboss.resteasy.client.jaxrs.engines.ManualClosingApacheHttpClient43Engine.writeRequestBodyToOutputStream(ManualClosingApacheHttpClient43Engine.java:584)
                at org.jboss.resteasy.client.jaxrs.engines.ManualClosingApacheHttpClient43Engine.buildEntity(ManualClosingApacheHttpClient43Engine.java:547)
                at org.jboss.resteasy.client.jaxrs.engines.ManualClosingApacheHttpClient43Engine.loadHttpMethod(ManualClosingApacheHttpClient43Engine.java:454)
                at org.jboss.resteasy.client.jaxrs.engines.ManualClosingApacheHttpClient43Engine.invoke(ManualClosingApacheHttpClient43Engine.java:264)
```

**Comment by praburajan** [comment]
Attaching the runtime classpath dependency tree from gradle output
[deps.txt](https://github.com/oracle/oci-java-sdk/files/4983138/deps.txt)

**Comment by praburajan** [comment]
I have followed the [OCI SDK documentation](https://docs.cloud.oracle.com/en-us/iaas/Content/API/SDKDocs/javasdkconfig.htm) to configure it to work with resteasy jaxrs implementation.  I am using oci sdk version 1.18.1. I am now getting the following exception 

```
Caused by: java.lang.NoSuchFieldError: INSTANCE
	at org.jboss.resteasy.core.providerfactory.ResteasyProviderFactoryImpl.initializeCommon(ResteasyProviderFactoryImpl.java:224)
	at org.jboss.resteasy.core.providerfactory.ResteasyProviderFactoryImpl.initialize(ResteasyProviderFactoryImpl.java:261)
	at org.jboss.resteasy.spi.ResteasyProviderFactory.<init>(ResteasyProviderFactory.java:293)
	at org.jboss.resteasy.core.providerfactory.ResteasyProviderFactoryImpl.<init>(ResteasyProviderFactoryImpl.java:148)
	at org.jboss.resteasy.client.jaxrs.internal.LocalResteasyProviderFactory.<init>(LocalResteasyProviderFactory.java:21)
	at org.jboss.resteasy.client.jaxrs.internal.ResteasyClientBuilderImpl.withConfig(ResteasyClientBuilderImpl.java:502)
	at org.jboss.resteasy.client.jaxrs.internal.ResteasyClientBuilderImpl.withConfig(ResteasyClientBuilderImpl.java:43)
	at com.oracle.bmc.http.DefaultConfigurator.setConnectorProvider(DefaultConfigurator.java:130)
	at com.oracle.bmc.http.DefaultConfigurator$NonBuffering.setConnectorProvider(DefaultConfigurator.java:162)
	at com.oracle.bmc.http.DefaultConfigurator.customizeBuilder(DefaultConfigurator.java:83)
	at com.oracle.bmc.http.CompositeClientConfigurator.customizeBuilder(CompositeClientConfigurator.java:41)
	at com.oracle.bmc.http.internal.RestClientFactory.createClient(RestClientFactory.java:167)
	at com.oracle.bmc.http.internal.RestClientFactory.create(RestClientFactory.java:146)
	at com.oracle.bmc.objectstorage.ObjectStorageClient.<init>(ObjectStorageClient.java:292)
	at com.oracle.bmc.objectstorage.ObjectStorageClient.<init>(ObjectStorageClient.java:217)
	at com.oracle.bmc.objectstorage.ObjectStorageClient$Builder.build(ObjectStorageClient.java:377)
```

**Comment by y-chandra** [comment]
It seems like this error is due to a version mismatch between RESTEasy client libraries... 
Please read : https://stackoverflow.com/questions/27371495/java-lang-nosuchfielderror-instance-in-apache-httpcomonents-and-wildfly

This also seems related to https://github.com/oracle/oci-java-sdk/issues/61, where a similar error is because of a version mismatch between Jersey client libraries (Jersey and Jackson)... But since you're using RESTEasy instead of Jersey, this might be due to a version mismatch between RESTEasy and RESTEasy Jackson client libraries...

**Comment by y-chandra** [comment]
@praburajan Were you able to resolve this issue?

**Comment by praburajan** [comment]
Yes, I was able to resolve it.

//I had to do the following
exclude group: "org.jboss.resteasy", module: "resteasy-client-microprofile"

implementation("org.glassfish.jersey.ext.microprofile:jersey-mp-rest-client:${versions.jerseyMpRestClientVersion}")
{
        exclude group: "org.glassfish.jersey.core", module: "jersey-server"
    }
implementation
"org.glassfish.jersey.ext.microprofile:jersey-mp-config:${versions.jerseyMpConfig}"
implementation
"org.apache.geronimo.config:geronimo-config-impl:${versions.geronimoConfigImplVersion}"

**Comment by ggoggodec80** [comment]
13:47:33.175 [main] DEBUG com.oracle.bmc.http.internal.LogHeadersFilter - Sending header 'Content-Length' with value '[4]'
13:47:33.175 [main] DEBUG com.oracle.bmc.http.internal.LogHeadersFilter - Sending header 'Content-Type' with value '[application/octet-stream]'
13:47:33.175 [main] DEBUG com.oracle.bmc.http.internal.LogHeadersFilter - Sending header 'date' with value '[Fri, 05 Mar 2021 04:47:33 GMT]'
13:47:33.175 [main] DEBUG com.oracle.bmc.http.internal.LogHeadersFilter - Sending header 'host' with value '[objectstorage.ap-seoul-1.oraclecloud.com]'
13:47:33.176 [main] DEBUG com.oracle.bmc.http.internal.LogHeadersFilter - Sending header 'opc-client-info' with value '[Oracle-JavaSDK/1.32.1]'
13:47:33.176 [main] DEBUG com.oracle.bmc.http.internal.LogHeadersFilter - Sending header 'opc-request-id' with value '[09D8E66405A64B619CC2D80FAA712552]'
13:47:33.176 [main] DEBUG com.oracle.bmc.http.internal.LogHeadersFilter - Sending header 'User-Agent' with value '[Oracle-JavaSDK/1.32.1 (Windows 10/10.0; Java/11.0.9.1; OpenJDK 64-Bit Server VM/11.0.9.1+11-b1145.77)]'
13:47:33.176 [main] DEBUG org.jboss.resteasy.resteasy_jaxrs.i18n - Interceptor Context: org.jboss.resteasy.core.interception.jaxrs.ClientWriterInterceptorContext,  Method : proceed
13:47:33.177 [main] DEBUG org.jboss.resteasy.client.jaxrs.i18n - RESTEASY004672: Client send processing failure.
javax.ws.rs.ProcessingException: RESTEASY003215: could not find writer for content-type application/octet-stream type: com.oracle.bmc.io.internal.KeepOpenInputStream
	at org.jboss.resteasy.core.interception.jaxrs.ClientWriterInterceptorContext.throwWriterNotFoundException(ClientWriterInterceptorContext.java:50)
	at org.jboss.resteasy.core.interception.jaxrs.AbstractWriterInterceptorContext.getWriter(AbstractWriterInterceptorContext.java:302)
	at org.jboss.resteasy.core.interception.jaxrs.AbstractWriterInterceptorContext.syncProceed(AbstractWriterInterceptorContext.java:240)
	at org.jboss.resteasy.core.interception.jaxrs.AbstractWriterInterceptorContext.proceed(AbstractWriterInterceptorContext.java:224)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.writeRequestBody(ClientInvocation.java:444)
	at org.jboss.resteasy.client.jaxrs.engines.ManualClosingApacheHttpClient43Engine.writeRequestBodyToOutputStream(ManualClosingApacheHttpClient43Engine.java:601)
	at org.jboss.resteasy.client.jaxrs.engines.ManualClosingApacheHttpClient43Engine.buildEntity(ManualClosingApacheHttpClient43Engine.java:560)
	at org.jboss.resteasy.client.jaxrs.engines.ManualClosingApacheHttpClient43Engine.loadHttpMethod(ManualClosingApacheHttpClient43Engine.java:465)
	at org.jboss.resteasy.client.jaxrs.engines.ManualClosingApacheHttpClient43Engine.invoke(ManualClosingApacheHttpClient43Engine.java:275)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:492)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:67)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocationBuilder.put(ClientInvocationBuilder.java:208)
	at com.oracle.bmc.http.internal.ForwardingInvocationBuilder.put(ForwardingInvocationBuilder.java:142)
	at com.oracle.bmc.http.internal.RestClient.lambda$put$12(RestClient.java:542)
	at com.oracle.bmc.http.internal.RestClient.put(RestClient.java:542)
	at com.oracle.bmc.objectstorage.ObjectStorageClient.lambda$null$78(ObjectStorageClient.java:1628)
	at com.oracle.bmc.retrier.BmcGenericRetrier.doFunctionCall(BmcGenericRetrier.java:89)
	at com.oracle.bmc.retrier.BmcGenericRetrier.lambda$execute$0(BmcGenericRetrier.java:60)
	at com.oracle.bmc.waiter.GenericWaiter.execute(GenericWaiter.java:55)
	at com.oracle.bmc.retrier.BmcGenericRetrier.execute(BmcGenericRetrier.java:51)
	at com.oracle.bmc.objectstorage.ObjectStorageClient.lambda$putObject$79(ObjectStorageClient.java:1623)
	at com.oracle.bmc.retrier.BmcGenericRetrier.doFunctionCall(BmcGenericRetrier.java:89)
	at com.oracle.bmc.retrier.BmcGenericRetrier.lambda$execute$0(BmcGenericRetrier.java:60)
	at com.oracle.bmc.waiter.GenericWaiter.execute(GenericWaiter.java:55)
	at com.oracle.bmc.retrier.BmcGenericRetrier.execute(BmcGenericRetrier.java:51)
	at com.oracle.bmc.objectstorage.ObjectStorageClient.putObject(ObjectStorageClient.java:1617)
	at com.oracle.bmc.objectstorage.transfer.UploadManager.singleUpload(UploadManager.java:137)
	at com.oracle.bmc.objectstorage.transfer.UploadManager.upload(UploadManager.java:100)
	at net.ion.live.DailyEndLiveStreamWithScript_test.uploadObjectStorage(DailyEndLiveStreamWithScript_test.java:84)
	at net.ion.live.DailyEndLiveStreamWithScript_test.main(DailyEndLiveStreamWithScript_test.java:32)
13:47:33.178 [main] DEBUG com.oracle.bmc.retrier.Retriers - mark/reset is supported, resetting stream com.oracle.bmc.io.internal.KeepOpenInputStream
13:47:33.180 [main] DEBUG com.oracle.bmc.retrier.BmcGenericRetrier - Not retrying, not retriable: (-1, null, false) Processing exception while communicating to: https://objectstorage.ap-seoul-1.oraclecloud.com (outbound opc-request-id: 09D8E66405A64B619CC2D80FAA712552)
13:47:33.180 [main] DEBUG com.oracle.bmc.waiter.GenericWaiter - Sleeping for 100ms, context at: WaiterConfiguration.WaitContext(startTime=1614919652618, attemptsMade=4, currentTime=1614919653180)









**What should I do?, This porject maven**


pom.xml

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>net.ion.st</groupId>
    <artifactId>downloaderFromRTSP_v2-oracle</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
    </properties>

    <dependencies>

        
        <dependency>
            <groupId>jakarta.ws.rs</groupId>
            <artifactId>jakarta.ws.rs-api</artifactId>
            <version>3.0.0</version>
        </dependency>


        
        <dependency>
            <groupId>joda-time</groupId>
            <artifactId>joda-time</artifactId>
            <version>2.1</version>
        </dependency>

        
        <dependency>
            <groupId>javax.annotation</groupId>
            <artifactId>javax.annotation-api</artifactId>
            <version>1.3.2</version>
        </dependency>
        <dependency>
            <groupId>org.mybatis.spring.boot</groupId>
            <artifactId>mybatis-spring-boot-starter</artifactId>
            <version>2.1.3</version>
        </dependency>
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>8.0.20</version>
        </dependency>
        
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>3.10</version>
        </dependency>

        
        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
            <version>2.6</version>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.9.8</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
            <version>2.9.8</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
            <version>2.9.8</version>
        </dependency>

        
        <dependency>
            <groupId>com.oracle.oci.sdk</groupId>
            <artifactId>oci-java-sdk-core</artifactId>
            <version>1.32.1</version>
        </dependency>

        
        <dependency>
            <groupId>com.oracle.oci.sdk</groupId>
            <artifactId>oci-java-sdk-objectstorage</artifactId>
            <version>1.32.1</version>
        </dependency>

        
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>30.0-jre</version>
        </dependency>

        
        <dependency>
            <groupId>javax.ws.rs</groupId>
            <artifactId>javax.ws.rs-api</artifactId>
            <version>2.1.1</version>
        </dependency>

        
        <dependency>
            <groupId>javax.ws.rs</groupId>
            <artifactId>javax.ws.rs-api</artifactId>
            <version>2.1</version>
        </dependency>

        
        <dependency>
            <groupId>org.glassfish.jersey.core</groupId>
            <artifactId>jersey-common</artifactId>
            <version>2.29</version>
        </dependency>

        
        <dependency>
            <groupId>org.glassfish.jersey.inject</groupId>
            <artifactId>jersey-hk2</artifactId>
            <version>2.27</version>
        </dependency>

        
        <dependency>
            <groupId>com.oracle.oci.sdk</groupId>
            <artifactId>oci-java-sdk-circuitbreaker</artifactId>
            <version>1.32.1</version>
        </dependency>

        
        <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcprov-jdk15on</artifactId>
            <version>1.68</version>
        </dependency>


        
        <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcpkix-jdk15on</artifactId>
            <version>1.68</version>
        </dependency>

        
        <dependency>
            <groupId>org.jboss.resteasy</groupId>
            <artifactId>resteasy-client</artifactId>
            <version>4.6.0.Final</version>
        </dependency>

        
        <dependency>
            <groupId>org.reactivestreams</groupId>
            <artifactId>reactive-streams</artifactId>
            <version>1.0.0.final</version>
        </dependency>


    </dependencies>

</project>
