### ISSUE TITLE
Create user does not working for not home region

### ISSUE THREAD

**Issue by Madzi** [oracle/oci-java-sdk#250]
When I try to create user in different region I got exception:
```
[INFO] 2020-09-11 14:45:33,862 [main] oracle.aiapps.common.oci.identity.support.IdentityServiceSupport - Creating user: 'x-test-user' (should be deleted) in 'ocid1.tenancy.oc1..aaaaaaaajxvb5q6itprsnmbkpmz2ott6tuzwywpseo5m5big2mgofghg6jza'
[ERROR] 2020-09-11 14:45:34,127 [main] oracle.aiapps.onboarding.core.ApplicationReadyListener - Unable to create/delete OCI account
[ERROR] 2020-09-11 14:45:34,134 [main] org.springframework.boot.SpringApplication - Application run failed
java.lang.IllegalStateException: OCI account has not permission to create OCI accounts
	at oracle.aiapps.onboarding.core.ApplicationReadyListener.onApplicationEvent(ApplicationReadyListener.java:34)
	at oracle.aiapps.onboarding.core.ApplicationReadyListener.onApplicationEvent(ApplicationReadyListener.java:14)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:402)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:359)
	at org.springframework.boot.context.event.EventPublishingRunListener.running(EventPublishingRunListener.java:103)
	at org.springframework.boot.SpringApplicationRunListeners.running(SpringApplicationRunListeners.java:77)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:327)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1214)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1203)
	at oracle.aiapps.onboarding.core.CoreOnboardingApplication.main(CoreOnboardingApplication.java:9)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:578)
Caused by: oracle.aiapps.common.oci.identity.IdentityServiceException: Unable to process request
	at oracle.aiapps.common.oci.identity.support.IdentityServiceSupport.createUser(IdentityServiceSupport.java:552)
	at oracle.aiapps.common.oci.identity.IdentityService.createUser(IdentityService.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at oracle.aiapps.common.oci.identity.support.transaction.TransactionalOperationInterceptor.invoke(TransactionalOperationInterceptor.java:17)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy132.createUser(Unknown Source)
	at oracle.aiapps.onboarding.core.ApplicationReadyListener.onApplicationEvent(ApplicationReadyListener.java:30)
	... 20 more
Caused by: com.oracle.bmc.model.BmcException: (403, NotAllowed, false) Please go to your home region IAD to execute CREATE, UPDATE and DELETE operations. (opc-request-id: 3473E4DC23F94BD9B5A1CC71CABEB750/95C9741C5CBC2EFBB1A1BB4EF6B9D75C/30F78C8CF2747A8462356AD478973BC2)
	at com.oracle.bmc.http.internal.ResponseHelper.throwIfNotSuccessful(ResponseHelper.java:138)
	at com.oracle.bmc.http.internal.ResponseConversionFunctionFactory$ValidatingParseResponseFunction.apply(ResponseConversionFunctionFactory.java:88)
	at com.oracle.bmc.http.internal.ResponseConversionFunctionFactory$ValidatingParseResponseFunction.apply(ResponseConversionFunctionFactory.java:84)
	at com.oracle.bmc.identity.internal.http.CreateUserConverter$1.apply(CreateUserConverter.java:67)
	at com.oracle.bmc.identity.internal.http.CreateUserConverter$1.apply(CreateUserConverter.java:55)
	at com.oracle.bmc.identity.IdentityClient.lambda$null$52(IdentityClient.java:1280)
	at com.oracle.bmc.retrier.BmcGenericRetrier.doFunctionCall(BmcGenericRetrier.java:88)
	at com.oracle.bmc.retrier.BmcGenericRetrier.lambda$execute$0(BmcGenericRetrier.java:59)
	at com.oracle.bmc.waiter.GenericWaiter.execute(GenericWaiter.java:55)
	at com.oracle.bmc.retrier.BmcGenericRetrier.execute(BmcGenericRetrier.java:50)
	at com.oracle.bmc.identity.IdentityClient.lambda$createUser$53(IdentityClient.java:1272)
	at com.oracle.bmc.retrier.BmcGenericRetrier.doFunctionCall(BmcGenericRetrier.java:88)
	at com.oracle.bmc.retrier.BmcGenericRetrier.lambda$execute$0(BmcGenericRetrier.java:59)
	at com.oracle.bmc.waiter.GenericWaiter.execute(GenericWaiter.java:55)
	at com.oracle.bmc.retrier.BmcGenericRetrier.execute(BmcGenericRetrier.java:50)
	at com.oracle.bmc.identity.IdentityClient.createUser(IdentityClient.java:1266)
	at oracle.aiapps.common.oci.identity.support.IdentityServiceSupport.createUser(IdentityServiceSupport.java:543)
```

How it's possible to create user in different region ?

**Comment by jodoglevy** [comment]
Hi @Madzi  - it is not possible to create users outside of your home region. As the error message says, please create users in your home region. They will be propagated to other regions for your tenancy automatically

**Comment by jodoglevy** [comment]
@Madzi - since I haven't heard back from you in 20 days, and provided response that this is by design, I'm going to close this issue.
