### ISSUE TITLE
Cannot deserialize value of type `com.oracle.bmc.database.model.AutonomousDatabaseSummary$PermissionLevel` from String "UNRESTRICTED": not one of the values accepted for Enum class: [Restricted, Unrestricted, UnknownEnumValue]

### ISSUE THREAD

**Issue by loiclefevre** [oracle/oci-java-sdk#259]
Listing Autonomous databases from a given compartment seems to be broken because of some Enum mismatch?

Tested with OCI SDK for Java v1.24.0 and v1.25.0, both give this error.

Full stacktrace:
Caused by: com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `com.oracle.bmc.database.model.AutonomousDatabaseSummary$PermissionLevel` from String "UNRESTRICTED": not one of the values accepted for Enum class: [Restricted, Unrestricted, UnknownEnumValue]
 at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 1, column: 2488] (through reference chain: java.util.ArrayList[0]->com.oracle.bmc.database.model.AutonomousDatabaseSummary$Builder["permissionLevel"])
        at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:1676)
        at com.fasterxml.jackson.databind.DeserializationContext.handleWeirdStringValue(DeserializationContext.java:932)
        at com.fasterxml.jackson.databind.deser.std.EnumDeserializer._deserializeAltString(EnumDeserializer.java:255)
        at com.fasterxml.jackson.databind.deser.std.EnumDeserializer.deserialize(EnumDeserializer.java:179)
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeSetAndReturn(MethodProperty.java:158)
        at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.vanillaDeserialize(BuilderBasedDeserializer.java:269)
        at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.deserialize(BuilderBasedDeserializer.java:193)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
        at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:1682)
        at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:977)
        at org.glassfish.jersey.jackson.internal.jackson.jaxrs.base.ProviderBase.readFrom(ProviderBase.java:838)
        at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.invokeReadFrom(ReaderInterceptorExecutor.java:257)
        at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.aroundReadFrom(ReaderInterceptorExecutor.java:236)
        at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:156)
        at org.glassfish.jersey.message.internal.MessageBodyFactory.readFrom(MessageBodyFactory.java:1091)
        at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:874)
        ... 30 more

**Comment by mricken** [comment]
We believe this only affects you if you use the DropWizard framework.

In order for the dropwizard framework to deserialize enums that come in as header or query parameters, the enum class needs to have a `fromString` method, which is used as the factory method by DropWizard's conversion logic. We are working on adding this method.

The issue doesn't exist for enums in payloads as the normal Jackson (json) deserialization handles those.

**Comment by loiclefevre** [comment]
Seems related to GraalVM native image building... Apparently the changes in the classes (new fields made the native image metadata out of date: reflect-config.json).
