### ISSUE TITLE
Object Storage SDK does not work with JBoss RESTEASY HttpClient ? 

### ISSUE THREAD

**Issue by ggoggodec80** [oracle/oci-java-sdk#288]
**pom.xml**

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>net.ion.st</groupId>
    <artifactId>downloaderFromRTSP_v2-oracle</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
    </properties>

    <dependencies>

        
        <dependency>
            <groupId>jakarta.ws.rs</groupId>
            <artifactId>jakarta.ws.rs-api</artifactId>
            <version>3.0.0</version>
        </dependency>

        
        <dependency>
            <groupId>joda-time</groupId>
            <artifactId>joda-time</artifactId>
            <version>2.1</version>
        </dependency>

        
        <dependency>
            <groupId>javax.annotation</groupId>
            <artifactId>javax.annotation-api</artifactId>
            <version>1.3.2</version>
        </dependency>
        <dependency>
            <groupId>org.mybatis.spring.boot</groupId>
            <artifactId>mybatis-spring-boot-starter</artifactId>
            <version>2.1.3</version>
        </dependency>
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>8.0.20</version>
        </dependency>
        
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>3.10</version>
        </dependency>

        
        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
            <version>2.6</version>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.9.8</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
            <version>2.9.8</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
            <version>2.9.8</version>
        </dependency>

        
        <dependency>
            <groupId>com.oracle.oci.sdk</groupId>
            <artifactId>oci-java-sdk-core</artifactId>
            <version>1.32.1</version>
        </dependency>

        
        <dependency>
            <groupId>com.oracle.oci.sdk</groupId>
            <artifactId>oci-java-sdk-objectstorage</artifactId>
            <version>1.32.1</version>
        </dependency>

        
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>30.0-jre</version>
        </dependency>

        
        <dependency>
            <groupId>javax.ws.rs</groupId>
            <artifactId>javax.ws.rs-api</artifactId>
            <version>2.1.1</version>
        </dependency>

        
        <dependency>
            <groupId>javax.ws.rs</groupId>
            <artifactId>javax.ws.rs-api</artifactId>
            <version>2.1</version>
        </dependency>

        
        <dependency>
            <groupId>org.glassfish.jersey.core</groupId>
            <artifactId>jersey-common</artifactId>
            <version>2.29</version>
        </dependency>

        
        <dependency>
            <groupId>org.glassfish.jersey.inject</groupId>
            <artifactId>jersey-hk2</artifactId>
            <version>2.27</version>
        </dependency>

        
        <dependency>
            <groupId>com.oracle.oci.sdk</groupId>
            <artifactId>oci-java-sdk-circuitbreaker</artifactId>
            <version>1.32.1</version>
        </dependency>

        
        <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcprov-jdk15on</artifactId>
            <version>1.68</version>
        </dependency>

        
        <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcpkix-jdk15on</artifactId>
            <version>1.68</version>
        </dependency>

        
        <dependency>
            <groupId>org.jboss.resteasy</groupId>
            <artifactId>resteasy-client</artifactId>
            <version>4.6.0.Final</version>
        </dependency>

        
        <dependency>
            <groupId>org.reactivestreams</groupId>
            <artifactId>reactive-streams</artifactId>
            <version>1.0.0.final</version>
        </dependency>

    </dependencies>

</project>

**source :** 

13:47:33.305 [main] DEBUG com.oracle.bmc.http.internal.LogHeadersFilter - Sending header 'User-Agent' with value '[Oracle-JavaSDK/1.32.1 (Windows 10/10.0; Java/11.0.9.1; OpenJDK 64-Bit Server VM/11.0.9.1+11-b1145.77)]'
13:47:33.306 [main] DEBUG org.jboss.resteasy.resteasy_jaxrs.i18n - Interceptor Context: org.jboss.resteasy.core.interception.jaxrs.ClientWriterInterceptorContext,  Method : proceed
13:47:33.312 [main] DEBUG org.jboss.resteasy.client.jaxrs.i18n - RESTEASY004672: Client send processing failure.
javax.ws.rs.ProcessingException: RESTEASY003215: could not find writer for content-type application/octet-stream type: com.oracle.bmc.io.internal.KeepOpenInputStream
	at org.jboss.resteasy.core.interception.jaxrs.ClientWriterInterceptorContext.throwWriterNotFoundException(ClientWriterInterceptorContext.java:50)
	at org.jboss.resteasy.core.interception.jaxrs.AbstractWriterInterceptorContext.getWriter(AbstractWriterInterceptorContext.java:302)
	at org.jboss.resteasy.core.interception.jaxrs.AbstractWriterInterceptorContext.syncProceed(AbstractWriterInterceptorContext.java:240)
	at org.jboss.resteasy.core.interception.jaxrs.AbstractWriterInterceptorContext.proceed(AbstractWriterInterceptorContext.java:224)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.writeRequestBody(ClientInvocation.java:444)
	at org.jboss.resteasy.client.jaxrs.engines.ManualClosingApacheHttpClient43Engine.writeRequestBodyToOutputStream(ManualClosingApacheHttpClient43Engine.java:601)
	at org.jboss.resteasy.client.jaxrs.engines.ManualClosingApacheHttpClient43Engine.buildEntity(ManualClosingApacheHttpClient43Engine.java:560)
	at org.jboss.resteasy.client.jaxrs.engines.ManualClosingApacheHttpClient43Engine.loadHttpMethod(ManualClosingApacheHttpClient43Engine.java:465)
	at org.jboss.resteasy.client.jaxrs.engines.ManualClosingApacheHttpClient43Engine.invoke(ManualClosingApacheHttpClient43Engine.java:275)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:492)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:67)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocationBuilder.put(ClientInvocationBuilder.java:208)
	at com.oracle.bmc.http.internal.ForwardingInvocationBuilder.put(ForwardingInvocationBuilder.java:142)
	at com.oracle.bmc.http.internal.RestClient.lambda$put$12(RestClient.java:542)
	at com.oracle.bmc.http.internal.RestClient.put(RestClient.java:542)
	at com.oracle.bmc.objectstorage.ObjectStorageClient.lambda$null$78(ObjectStorageClient.java:1628)
	at com.oracle.bmc.retrier.BmcGenericRetrier.doFunctionCall(BmcGenericRetrier.java:89)
	at com.oracle.bmc.retrier.BmcGenericRetrier.lambda$execute$0(BmcGenericRetrier.java:60)
	at com.oracle.bmc.waiter.GenericWaiter.execute(GenericWaiter.java:55)
	at com.oracle.bmc.retrier.BmcGenericRetrier.execute(BmcGenericRetrier.java:51)
	at com.oracle.bmc.objectstorage.ObjectStorageClient.lambda$putObject$79(ObjectStorageClient.java:1623)
	at com.oracle.bmc.retrier.BmcGenericRetrier.doFunctionCall(BmcGenericRetrier.java:89)
	at com.oracle.bmc.retrier.BmcGenericRetrier.lambda$execute$0(BmcGenericRetrier.java:60)
	at com.oracle.bmc.waiter.GenericWaiter.execute(GenericWaiter.java:55)
	at com.oracle.bmc.retrier.BmcGenericRetrier.execute(BmcGenericRetrier.java:51)
	at com.oracle.bmc.objectstorage.ObjectStorageClient.putObject(ObjectStorageClient.java:1617)
	at com.oracle.bmc.objectstorage.transfer.UploadManager.singleUpload(UploadManager.java:137)
	at com.oracle.bmc.objectstorage.transfer.UploadManager.upload(UploadManager.java:100)
	at net.ion.live.DailyEndLiveStreamWithScript_test.uploadObjectStorage(DailyEndLiveStreamWithScript_test.java:84)
	at net.ion.live.DailyEndLiveStreamWithScript_test.main(DailyEndLiveStreamWithScript_test.java:32)
13:47:33.314 [main] DEBUG com.oracle.bmc.retrier.Retriers - mark/reset is supported, resetting stream com.oracle.bmc.io.internal.KeepOpenInputStream
13:47:33.314 [main] DEBUG com.oracle.bmc.retrier.BmcGenericRetrier - Not retrying, not retriable: (-1, null, false) Processing exception while communicating to:

**Comment by VidhiBhansali** [comment]
@ggoggodec80 Thanks for reaching out. I am not able to reproduce this issue on my end. Can you please elaborate when you are getting this issue. I have attached an example file for your reference.
[ResteasyClientWithUploadManagerExample.txt](https://github.com/oracle/oci-java-sdk/files/6326939/ResteasyClientWithUploadManagerExample.txt)

**Comment by VidhiBhansali** [comment]
@ggoggodec80 Were you able to resolve this issue?

**Comment by VidhiBhansali** [comment]
Closing this issue since there was no response. Please feel free to reopen if you still see the issue after updating the java-sdk version
