### ISSUE TITLE
ObjectStorage client throws java.lang.TypeNotPresentException

### ISSUE THREAD

**Issue by hadiyarajesh** [oracle/oci-java-sdk#335]
Below code is uploading object (.jpg file) successfully on oci sdk version `1.34.0`, but throw 
`java.lang.TypeNotPresentException: Type org.glassfish.jersey.spi.ComponentProvider not present` on versions above `1.34.0`

```
private val client: ObjectStorageClient,
val putObjectRequest = PutObjectRequest.builder()
                .namespaceName(nameSpaceName)
                .bucketName(bucketName)
                .objectName(objectName)
                .putObjectBody(file.inputStream())
                .build()
//Below line throws exception
val response = client.putObject(putObjectRequest)
```

Here's the full stacktrace
```
java.lang.TypeNotPresentException: Type org.glassfish.jersey.spi.ComponentProvider not present
	at java.base/sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:117) ~[na:na]
	at java.base/sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:125) ~[na:na]
	at java.base/sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49) ~[na:na]
	at java.base/sun.reflect.generics.visitor.Reifier.reifyTypeArguments(Reifier.java:68) ~[na:na]
	at java.base/sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:138) ~[na:na]
	at java.base/sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49) ~[na:na]
	at java.base/sun.reflect.generics.visitor.Reifier.reifyTypeArguments(Reifier.java:68) ~[na:na]
	at java.base/sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:138) ~[na:na]
	at java.base/sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49) ~[na:na]
	at java.base/sun.reflect.generics.visitor.Reifier.reifyTypeArguments(Reifier.java:68) ~[na:na]
	at java.base/sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:138) ~[na:na]
	at java.base/sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49) ~[na:na]
	at java.base/sun.reflect.generics.repository.ClassRepository.computeSuperclass(ClassRepository.java:104) ~[na:na]
	at java.base/sun.reflect.generics.repository.ClassRepository.getSuperclass(ClassRepository.java:86) ~[na:na]
	at java.base/java.lang.Class.getGenericSuperclass(Class.java:949) ~[na:na]
	at javax.ws.rs.core.GenericType.getTypeArgument(GenericType.java:211) ~[jakarta.ws.rs-api-2.1.6.jar:2.1.6]
	at javax.ws.rs.core.GenericType.<init>(GenericType.java:117) ~[jakarta.ws.rs-api-2.1.6.jar:2.1.6]
	at org.glassfish.jersey.client.ClientBootstrapBag$1.<init>(ClientBootstrapBag.java:55) ~[jersey-client-2.34.jar:na]
	at org.glassfish.jersey.client.ClientBootstrapBag.getComponentProviders(ClientBootstrapBag.java:55) ~[jersey-client-2.34.jar:na]
	at org.glassfish.jersey.client.ClientConfig$State.initRuntime(ClientConfig.java:447) ~[jersey-client-2.34.jar:na]
	at org.glassfish.jersey.internal.util.collection.Values$LazyValueImpl.get(Values.java:317) ~[jersey-common-2.33.jar:na]
	at org.glassfish.jersey.client.ClientConfig.getRuntime(ClientConfig.java:819) ~[jersey-client-2.34.jar:na]
	at org.glassfish.jersey.client.ClientRequest.getClientRuntime(ClientRequest.java:176) ~[jersey-client-2.34.jar:na]
	at org.glassfish.jersey.client.ClientRequest.getInjectionManager(ClientRequest.java:567) ~[jersey-client-2.34.jar:na]
	at org.glassfish.jersey.client.JerseyWebTarget.onBuilder(JerseyWebTarget.java:371) ~[jersey-client-2.34.jar:na]
	at org.glassfish.jersey.client.JerseyWebTarget.request(JerseyWebTarget.java:199) ~[jersey-client-2.34.jar:na]
	at org.glassfish.jersey.client.JerseyWebTarget.request(JerseyWebTarget.java:38) ~[jersey-client-2.34.jar:na]
	at com.oracle.bmc.http.internal.WrappedWebTarget.request(WrappedWebTarget.java:82) ~[oci-java-sdk-common-2.6.0.jar:na]
	at com.oracle.bmc.objectstorage.internal.http.PutObjectConverter.fromRequest(PutObjectConverter.java:51) ~[oci-java-sdk-objectstorage-generated-2.6.0.jar:na]
	at com.oracle.bmc.objectstorage.ObjectStorageClient.putObject(ObjectStorageClient.java:1625) ~[oci-java-sdk-objectstorage-generated-2.6.0.jar:na]
```

**Comment by jodoglevy** [comment]
@hadiyarajesh thanks for reporting - we'll take a look

**Comment by hadiyarajesh** [comment]
@jodoglevy is there any update on this?

**Comment by y-chandra** [comment]
@hadiyarajesh - It seems like one of your project dependencies is bringing in a conflicting version of `org.glassfish.jersey.*`. The SDK versions >= `1.36.5` uses version `2.34` of `org.glassfish.jersey.*` dependencies. Please make sure all the `org.glassfish.jersey.*` packages are of the same version. You can run a maven dependency tree with verbose on to see which other dependencies might be pulling in the dependencies.

**Comment by y-chandra** [comment]
@hadiyarajesh - Were you able to resolve the issue? We'll be closing this ticket soon if we don't hear back from you, feel free to reopen it if you're unable to resolve the issue

**Comment by hadiyarajesh** [comment]
Yes, @y-chandra. Please close the issue. Thank you.
