### ISSUE TITLE
List pluggable Request is failing with invalid pagination token even no page valued provided in request

### ISSUE THREAD

**Issue by avinashkumar2021** [oracle/oci-java-sdk#337]
com.oracle.bmc.model.BmcException: (400, InvalidParameter, false) Invalid pagination token (opc-request-id: 421FB0B4B77946C58BCAA96E14857B60/BC18C93E6CEE0BA5BC2BF6BD7F8EA9A5/D9B5673A62E1D034B0EADE9F9682A554)

 at com.oracle.bmc.http.internal.ResponseHelper.throwIfNotSuccessful(ResponseHelper.java:140)

 at com.oracle.bmc.http.internal.ResponseConversionFunctionFactory$ValidatingParseResponseFunction.apply(ResponseConversionFunctionFactory.java:88)

 at com.oracle.bmc.http.internal.ResponseConversionFunctionFactory$ValidatingParseResponseFunction.apply(ResponseConversionFunctionFactory.java:84)

 at com.oracle.bmc.database.internal.http.ListPluggableDatabasesConverter$1.apply(ListPluggableDatabasesConverter.java:143)

 at com.oracle.bmc.database.internal.http.ListPluggableDatabasesConverter$1.apply(ListPluggableDatabasesConverter.java:119)

 at com.oracle.bmc.database.DatabaseClient.lambda$null$352(DatabaseClient.java:6140)

 at com.oracle.bmc.retrier.BmcGenericRetrier.doFunctionCall(BmcGenericRetrier.java:89)

 at com.oracle.bmc.retrier.BmcGenericRetrier.lambda$execute$0(BmcGenericRetrier.java:60)

 at com.oracle.bmc.waiter.GenericWaiter.execute(GenericWaiter.java:55)

 at com.oracle.bmc.retrier.BmcGenericRetrier.execute(BmcGenericRetrier.java:51)

 at com.oracle.bmc.database.DatabaseClient.lambda$listPluggableDatabases$353(DatabaseClient.java:6136)

 at com.oracle.bmc.retrier.BmcGenericRetrier.doFunctionCall(BmcGenericRetrier.java:89)

 at com.oracle.bmc.retrier.BmcGenericRetrier.lambda$execute$0(BmcGenericRetrier.java:60)

 at com.oracle.bmc.waiter.GenericWaiter.execute(GenericWaiter.java:55)

 at com.oracle.bmc.retrier.BmcGenericRetrier.execute(BmcGenericRetrier.java:51)

 at com.oracle.bmc.database.DatabaseClient.listPluggableDatabases(DatabaseClient.java:6130)

Request - 
ListPluggableDatabasesRequest(super=com.oracle.bmc.database.requests.ListPluggableDatabasesRequest@c00cd540, compartmentId=null, databaseId=ocid1.database.region1.*****, limit=null, page=null, sortBy=Timecreated, sortOrder=Desc, lifecycleState=null, pdbName=null)

**Comment by KartikShrikantHegde** [comment]
Hi @avinashkumar2021 , our database team tried to reproduce this scenario and they confirmed to me that the`List pluggable Request` API call is behaving as expected on their end. Could you please try again with a newer version of the Java SDK and confirm if you are still facing the issue?

**Comment by KartikShrikantHegde** [comment]
Hi @avinashkumar2021 , I am closing the issue for now, please feel free to re-open if you run into issues again. Thanks.
