### ISSUE TITLE
Caused by: javax.ws.rs.ProcessingException: javax.net.ssl.SSLHandshakeException: No X509TrustManager implementation available

### ISSUE THREAD

**Issue by gmhoolageri** [oracle/oci-java-sdk#397]
We were using JDK version 8 with OCI JAVA SDK 2.13.0. We migrated to JDK 11 and we are seeing strange issue after this. Even upgraded to latest JAVA SDK and found the same issue.

The OCI JAVA SDK calls work sometime and does not work sometime. When code does not work it throws an exception - 

```
_[2022-05-05 10:29:36,201] [ERROR] [BlockVolumeAssociatedServiceOCIImpl] - Encountered exception retrieving list of volume backup policies
**com.oracle.bmc.model.BmcException: (-1, null, false) Processing exception while communicating to: https://auth.us-phoenix-1.oraclecloud.com (outbound opc-request-id: 98BE42DE54FC4EE797CAD2823CFA42CF)**
	at com.oracle.bmc.http.internal.RestClient.convertToBmcException(RestClient.java:994) ~[oci-java-sdk-common-2.13.0.jar:?]
	at com.oracle.bmc.http.internal.RestClient.post(RestClient.java:306) ~[oci-java-sdk-common-2.13.0.jar:?]
	at com.oracle.bmc.auth.internal.X509FederationClient.makeCall(X509FederationClient.java:301) ~[oci-java-sdk-common-2.13.0.jar:?]
	at com.oracle.bmc.auth.internal.X509FederationClient.getSecurityTokenFromServer(X509FederationClient.java:282) ~[oci-java-sdk-common-2.13.0.jar:?]
	at com.oracle.bmc.auth.internal.X509FederationClient.refreshAndGetSecurityTokenInner(X509FederationClient.java:208) ~[oci-java-sdk-common-2.13.0.jar:?]
	at com.oracle.bmc.auth.internal.X509FederationClient.refreshAndGetSecurityToken(X509FederationClient.java:157) ~[oci-java-sdk-common-2.13.0.jar:?]
	at com.oracle.bmc.auth.InstancePrincipalsAuthenticationDetailsProvider.refresh(InstancePrincipalsAuthenticationDetailsProvider.java:57) ~[oci-java-sdk-common-2.13.0.jar:?]
	at com.oracle.bmc.auth.InstancePrincipalsAuthenticationDetailsProvider.refresh(InstancePrincipalsAuthenticationDetailsProvider.java:19) ~[oci-java-sdk-common-2.13.0.jar:?]
	at com.oracle.bmc.retrier.TokenRefreshRetrier.lambda$createTokenRefreshRetryConfiguration$0(TokenRefreshRetrier.java:44) ~[oci-java-sdk-common-2.13.0.jar:?]
	at com.oracle.bmc.retrier.BmcGenericRetrier.lambda$execute$0(BmcGenericRetrier.java:62) ~[oci-java-sdk-common-2.13.0.jar:?]
	at com.oracle.bmc.waiter.GenericWaiter.execute(GenericWaiter.java:55) ~[oci-java-sdk-common-2.13.0.jar:?]
	at com.oracle.bmc.retrier.BmcGenericRetrier.execute(BmcGenericRetrier.java:51) ~[oci-java-sdk-common-2.13.0.jar:?]
	at com.oracle.bmc.core.BlockstorageClient.lambda$listVolumeBackupPolicies$89(BlockstorageClient.java:1887) ~[oci-java-sdk-core-2.13.0.jar:?]
	at com.oracle.bmc.retrier.BmcGenericRetrier.doFunctionCall(BmcGenericRetrier.java:89) ~[oci-java-sdk-common-2.13.0.jar:?]
	at com.oracle.bmc.retrier.BmcGenericRetrier.lambda$execute$0(BmcGenericRetrier.java:60) ~[oci-java-sdk-common-2.13.0.jar:?]
	at com.oracle.bmc.waiter.GenericWaiter.execute(GenericWaiter.java:55) ~[oci-java-sdk-common-2.13.0.jar:?]
	at com.oracle.bmc.retrier.BmcGenericRetrier.execute(BmcGenericRetrier.java:51) ~[oci-java-sdk-common-2.13.0.jar:?]
	at com.oracle.bmc.core.BlockstorageClient.listVolumeBackupPolicies(BlockstorageClient.java:1881) ~[oci-java-sdk-core-2.13.0.jar:?]
	at com.oracle.otm.otmservicemanager.connector.BlockVolumeAssociatedServiceOCIImpl.listVolumeBackupPolicies(BlockVolumeAssociatedServiceOCIImpl.java:720) [otmservicemanager.jar:?]
	at com.oracle.otm.otmservicemanager.connector.BlockVolumeAssociatedServiceOCIImpl$Proxy$_$$_WeldClientProxy.listVolumeBackupPolicies(Unknown Source) [otmservicemanager.jar:?]
	at com.oracle.otm.otmservicemanager.connector.services.BlockVolumeAssociatedService.listVolumeBackupPolicies(BlockVolumeAssociatedService.java:66) [otmservicemanager.jar:?]
	at com.oracle.otm.otmservicemanager.connector.services.BlockVolumeAssociatedService$Proxy$_$$_WeldClientProxy.listVolumeBackupPolicies(Unknown Source) [otmservicemanager.jar:?]
	at com.oracle.otm.otmservicemanager.tasks.PayloadProcessingBaseTask.retrieveListOfVolumeBackupPolicies(PayloadProcessingBaseTask.java:560) [otmservicemanager.jar:?]
	at com.oracle.otm.otmservicemanager.tasks.PayloadProcessingBaseTask.retrieveConfiguredBackupPolicyId(PayloadProcessingBaseTask.java:536) [otmservicemanager.jar:?]
	at com.oracle.otm.otmservicemanager.tasks.provisioning.TaskAssignBootVolumeBackupPolicy.callTask(TaskAssignBootVolumeBackupPolicy.java:23) [otmservicemanager.jar:?]
	at com.oracle.otm.otmservicemanager.tasks.Task.call(Task.java:54) [otmservicemanager.jar:?]
	at com.oracle.otm.otmservicemanager.tasks.Task.call(Task.java:18) [otmservicemanager.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: javax.ws.rs.ProcessingException: javax.net.ssl.SSLHandshakeException: No X509TrustManager implementation available
	at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:531) ~[jersey-apache-connector-2.35.jar:?]
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:297) ~[jersey-client-2.35.jar:?]
	at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$0(JerseyInvocation.java:662) ~[jersey-client-2.35.jar:?]
	at org.glassfish.jersey.client.JerseyInvocation.call(JerseyInvocation.java:697) ~[jersey-client-2.35.jar:?]
	at org.glassfish.jersey.client.JerseyInvocation.lambda$runInScope$3(JerseyInvocation.java:691) ~[jersey-client-2.35.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292) ~[jersey-common-2.35.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274) ~[jersey-common-2.35.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:205) ~[jersey-common-2.35.jar:?]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:390) ~[jersey-common-2.35.jar:?]
	at org.glassfish.jersey.client.JerseyInvocation.runInScope(JerseyInvocation.java:691) ~[jersey-client-2.35.jar:?]
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:661) ~[jersey-client-2.35.jar:?]
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:439) ~[jersey-client-2.35.jar:?]
	at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:345) ~[jersey-client-2.35.jar:?]
	at com.oracle.bmc.http.internal.ForwardingInvocationBuilder.post(ForwardingInvocationBuilder.java:157) ~[oci-java-sdk-common-2.13.0.jar:?]
	at com.oracle.bmc.http.internal.ForwardingInvocationBuilder.post(ForwardingInvocationBuilder.java:157) ~[oci-java-sdk-common-2.13.0.jar:?]
	at com.oracle.bmc.http.internal.RestClient.lambda$post$4(RestClient.java:304) ~[oci-java-sdk-common-2.13.0.jar:?]
	at com.oracle.bmc.circuitbreaker.internal.JaxRsCircuitBreakerImpl.lambda$decorateSupplier$0(JaxRsCircuitBreakerImpl.java:82) ~[oci-java-sdk-circuitbreaker-2.13.0.jar:?]
	at io.github.resilience4j.circuitbreaker.CircuitBreaker.lambda$decorateSupplier$4(CircuitBreaker.java:198) ~[resilience4j-circuitbreaker-1.2.0.jar:1.2.0]
	at com.oracle.bmc.circuitbreaker.internal.JaxRsCircuitBreakerImpl.lambda$decorateSupplier$1(JaxRsCircuitBreakerImpl.java:92) ~[oci-java-sdk-circuitbreaker-2.13.0.jar:?]
	at com.oracle.bmc.http.internal.RestClient.lambda$decorateSupplier$0(RestClient.java:175) ~[oci-java-sdk-common-2.13.0.jar:?]
	at com.oracle.bmc.http.internal.RestClient.post(RestClient.java:304) ~[oci-java-sdk-common-2.13.0.jar:?]
	... 29 more
**Caused by: javax.net.ssl.SSLHandshakeException: No X509TrustManager implementation available**
	at sun.security.ssl.Alert.createSSLException(Alert.java:131) ~[?:?]
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:368) ~[?:?]
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:311) ~[?:?]
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:306) ~[?:?]
	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:654) ~[?:?]
	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:473) ~[?:?]
	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:369) ~[?:?]
	at sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392) ~[?:?]
	at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:478) ~[?:?]
	at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:456) ~[?:?]
	at sun.security.ssl.TransportContext.dispatch(TransportContext.java:198) ~[?:?]
	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:172) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1377) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1290) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:411) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:383) ~[?:?]
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384) ~[httpclient-4.5.13.jar:4.5.13]_
```

### Following is one of many code point where problem is seen -

```
ListVolumeBackupPoliciesResponse listVolumeBackupPolicies = blockStorageClient.listVolumeBackupPolicies(
                    ListVolumeBackupPoliciesRequest.builder().compartmentId(compartmentOCID).build());
```

We are blocked because of this. Please suggest.

**Comment by y-chandra** [comment]
Could be related to the java TrustStore. Could you please try adding the certs using https://stackoverflow.com/questions/38353944/keep-getting-no-x509trustmanager-implementation-available-error-when-trying-to-c?

**Comment by y-chandra** [comment]
We'll be closing this issue if we don't hear back from you in a week. Please feel free to reopen if the problem persists.

**Comment by y-chandra** [comment]
Closing this issue for now. Please feel free to reopen if the problem persists.
