### ISSUE TITLE
Unable to Switch to Jersey Default HttpUrlConnectorProvider

### ISSUE THREAD

**Issue by gmhoolageri** [oracle/oci-java-sdk#399]
We have removed apache connector via exclusion list in pom.xml of maven but application throws following exception

```
Caused by: java.lang.ClassNotFoundException: org.glassfish.jersey.apache.connector.ApacheConnectionClosingStrategy
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) ~[?:?]
        at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at com.oracle.bmc.http.ApacheUtils.getApacheConnectionClosingStrategy(ApacheUtils.java:63) ~[oci-java-sdk-common-2.13.0.jar:?]
        at com.oracle.bmc.limits.LimitsClient.<init>(LimitsClient.java:245) ~[oci-java-sdk-limits-2.13.0.jar:?]
        at com.oracle.bmc.limits.LimitsClient.<init>(LimitsClient.java:181) ~[oci-java-sdk-limits-2.13.0.jar:?]
        at com.oracle.bmc.limits.LimitsClient.<init>(LimitsClient.java:146) ~[oci-java-sdk-limits-2.13.0.jar:?]
        at com.oracle.bmc.limits.LimitsClient.<init>(LimitsClient.java:118) ~[oci-java-sdk-limits-2.13.0.jar:?]
        at com.oracle.bmc.limits.LimitsClient.<init>(LimitsClient.java:93) ~[oci-java-sdk-limits-2.13.0.jar:?]
        at com.oracle.bmc.limits.LimitsClient.<init>(LimitsClient.java:70) ~[oci-java-sdk-limits-2.13.0.jar:?]
        at com.oracle.bmc.limits.LimitsClient.<init>(LimitsClient.java:56) ~[oci-java-sdk-limits-2.13.0.jar:?]
        at com.oracle.bmc.limits.LimitsClient.<init>(LimitsClient.java:45) ~[oci-java-sdk-limits-2.13.0.jar:?]
```

Exclusion

```
<dependency>
	<groupId>com.oracle.oci.sdk</groupId>
	<artifactId>oci-java-sdk-common</artifactId>
       <optional>false</optional>
	<exclusions>
		<exclusion>
			<groupId>org.glassfish.jersey.connectors</groupId>
			<artifactId>jersey-apache-connector</artifactId>
		</exclusion>
	</exclusions>
</dependency>
```

**Comment by y-chandra** [comment]
Please use either the env variable or code to switch back to the Jersey Default HttpUrlConnectorProvider - https://docs.oracle.com/en-us/iaas/Content/API/SDKDocs/javasdkconfig.htm

**Comment by y-chandra** [comment]
We'll be closing this issue if we don't hear back from you in a week. Please feel free to reopen if the problem persists.

**Comment by y-chandra** [comment]
Closing this issue, please feel free to reopen if the problem persists.
