### ISSUE TITLE
Dataflow bmc client sending multiple requests resulting in 409

### ISSUE THREAD

**Issue by jainbhavya53** [oracle/oci-java-sdk#407]
Hi Team
We are intermittently observing 409 response code while performing createApplication via dataflow bmc client. Upon looking into more detail we found out there were two requests made within 22 seconds(approx.). The later request got successful but the former request failed with 500 response code.

https://github.com/oracle/oci-java-sdk/blob/master/bmc-dataflow/src/main/java/com/oracle/bmc/dataflow/DataFlowClient.java#L594

We are using ```com.oracle.oci.sdk:oci-java-sdk-dataflow:jar:2.14.1-preview1-SNAPSHOT```  version, with the following config:

```
public DataFlowClient getDataFlowClient() {
  final RetryConfiguration DEFAULT_SERVICE_RETRY_CONFIG = RetryConfiguration.builder()
      .terminationStrategy(new MaxAttemptsTerminationStrategy(
          (config.getTestConfiguration().getMaxAttempts() == null) ? 5 : config.getTestConfiguration()
              .getMaxAttempts()))
      .delayStrategy(new ExponentialBackoffDelayStrategy(
          ((config.getTestConfiguration().getMaxDelayInMillis() == null) ? TimeUnit.SECONDS.toMillis(30) :
              config.getTestConfiguration().getMaxDelayInMillis())))
      .retryCondition(new DefaultRetryCondition())
      .build();
  Retriers.setDefaultRetryConfiguration(DEFAULT_SERVICE_RETRY_CONFIG);
  DataFlowClient client = new DataFlowClient(getAuthProvider(config), null);
  client.setEndpoint(config.getTestConfiguration().getEndpoint());
  return client;
}
```

Please look into the issue !

Thanks

**Comment by jainbhavya53** [comment]
First request failed and later request succeeded. Both the requests tried to update kiev and one of them succeeded, while the other failed with 409(CommitConflictException).

In splat we received 500 for the request which failed and 200 for the request which succeeded

On the client end, we received 409 exception.

**Logs for requests:**

**First request:  1652316363948ms ->  Thu May 12 00:46:03 UTC 2022**

```
{
  "level": "INFO",
  "logger": "oracle.dfcs.server.filter.MissingClientIdFilter",
  "thread": "dw-6775",
  "ts": 1652316363948,
  "msg": "opc-request-id requested.  Returning 2D9C43A6BB6B4877B99815B2473F4EF9/9A2041CD15858998DC08E537EDC037CA",
  "opc-request-id": "2D9C43A6BB6B4877B99815B2473F4EF9/9A2041CD15858998DC08E537EDC037CA/D1489DCC2C91020FA8C9BF2C5C6EE2C8"
}

{
  "level": "INFO",
  "logger": "oracle.dfcs.server.resources.ApplicationsResource",
  "ts": 1652316364009,
  "msg": "Received request to create an application",
  "opc-request-id": "2D9C43A6BB6B4877B99815B2473F4EF9/9A2041CD15858998DC08E537EDC037CA/D1489DCC2C91020FA8C9BF2C5C6EE2C8"
}
```

**Second request: 1652316386036ms -> Thu May 12 00:46:26 UTC 2022**

```
{
  "level": "INFO",
  "logger": "oracle.dfcs.server.filter.MissingClientIdFilter",
  "thread": "dw-6548",
  "ts": 1652316386036,
  "msg": "opc-request-id requested.  Returning 2D9C43A6BB6B4877B99815B2473F4EF9/B3D329331C0EAE4A6E9A90F8CAB5211D",
  "opc-request-id": "2D9C43A6BB6B4877B99815B2473F4EF9/B3D329331C0EAE4A6E9A90F8CAB5211D/D3C7909F04D0C08D7B5881D6FEDFABB8"
}

{
  "level": "INFO",
  "logger": "oracle.dfcs.server.resources.ApplicationsResource",
  "ts": 1652316386103,
  "msg": "Received request to create an application",
  "opc-request-id": "2D9C43A6BB6B4877B99815B2473F4EF9/B3D329331C0EAE4A6E9A90F8CAB5211D/D3C7909F04D0C08D7B5881D6FEDFABB8"
}
```

============================================================================================

**First request failed with 409 response code:**
```
{"level":"ERROR","logger":"oracle.dfcs.server.resources.ApplicationsResource","ts":1652316392076,"msg":"Failed to create 
application 
com.oracle.dfcs.dal.exceptions.DalException: Insert transaction failed
	at com.oracle.dfcs.dal.ApiApplicationResourceDataProvider.persistApplicationEntity(ApiApplicationResourceDataProvider.java:803)
	at com.oracle.dfcs.dal.ApiApplicationResourceDataProvider.createApplication(ApiApplicationResourceDataProvider.java:162)
	at oracle.dfcs.server.service.ApplicationManagementService.createApplication(ApplicationManagementService.java:159)
	at oracle.dfcs.server.resources.ApplicationsResource.createApplicationWithoutAuth(ApplicationsResource.java:347)
	at oracle.dfcs.server.resources.ApplicationsResource.createApplication(ApplicationsResource.java:255)
	at sun.reflect.GeneratedMethodAccessor827.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:219)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:475)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:397)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:255)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1626)
	at io.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:35)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at io.dropwizard.jersey.filter.AllowedMethodsFilter.handle(AllowedMethodsFilter.java:47)
	at io.dropwizard.jersey.filter.AllowedMethodsFilter.doFilter(AllowedMethodsFilter.java:41)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at com.oracle.pic.sherlock.collector.servlet.AuditFilter.doFilter(AuditFilter.java:154)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:319)
	at org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:273)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at com.oracle.pic.commons.service.RequestIdFilter.doFilter(RequestIdFilter.java:80)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at oracle.dfcs.server.filter.MissingClientIdFilter.doFilter(MissingClientIdFilter.java:62)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1434)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:249)
	at io.dropwizard.jetty.RoutingHandler.handle(RoutingHandler.java:52)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:713)
	at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:54)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:179)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:555)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:410)
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:164)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:386)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.oracle.pic.kiev.exceptions.CommitConflictException: (409, Conflict, false) (409, Conflict, false) CommitConflictExceptionStart {\"conflictingTransactionId\":32017239,\"bucketId\":1004,\"bucketName\":\"CREATE_RETRY_ENTITIES\",\"transactionKey\":\"TxKey(Type=WRITE, Bucket=1004, Index=0, keyHash=-592046436, isUnique=true, uniqueHash=Optional.empty)\"} CommitConflictExceptionEnd (opc-request-id: 69CF4EB87CEC4359A33C42602E124407/94360F4AA0E5578019A5B90525613C60/E4E8ED172E1AE13CAA600D87D37ACDAB) (opc-request-id: 69CF4EB87CEC4359A33C42602E124407/94360F4AA0E5578019A5B90525613C60/09628D620D7E1A4F8B076B59AE8125D2)
	at com.oracle.pic.kiev.client.TransactorClient.commit(TransactorClient.java:158)
	at com.oracle.pic.kiev.impl.TransactionImpl.commit(TransactionImpl.java:284)
	at com.oracle.pic.kiev.retryable.RetryableTransaction.lambda$commit$1(RetryableTransaction.java:60)
	at com.github.rholder.retry.AttemptTimeLimiters$NoAttemptTimeLimit.call(AttemptTimeLimiters.java:78)
	at com.github.rholder.retry.Retryer.call(Retryer.java:160)
	at com.oracle.pic.kiev.retryable.RetryHelper.call(RetryHelper.java:41)
	at com.oracle.pic.kiev.retryable.RetryableTransaction.commit(RetryableTransaction.java:59)
	at com.oracle.dfcs.dal.ApiApplicationResourceDataProvider.persistApplicationEntity(ApiApplicationResourceDataProvider.java:796)
	... 86 common frames omitted

","opc-request-id":"2D9C43A6BB6B4877B99815B2473F4EF9/9A2041CD15858998DC08E537EDC037CA/D1489DCC2C91020FA8C9BF2C5C6EE2C8"}
```

**Second request successful:**

```
{"level":"INFO","logger":"oracle.dfcs.server.resources.ApplicationsResource","ts":1652316391230,"msg":"Successfully created application","opc-request-id":"2D9C43A6BB6B4877B99815B2473F4EF9/B3D329331C0EAE4A6E9A90F8CAB5211D/D3C7909F04D0C08D7B5881D6FEDFABB8"}
```
============================================================================================

Splat logs:

First request:  Received 500 in splat

```
{"remoteHost":"x.x.x.x","remoteUser":"","ts":1652316392077,"elapsedTime":28130,"statusCode":500,"userAgent":"Oracle-JavaSDK/2.14.1-preview1-SNAPSHOT (Linux/4.14.35-2047.511.5.7.el7uek.x86_64; Java/1.8.0_301; Java HotSpot(TM) 64-Bit Server VM GraalVM EE 20.3.3/25.301-b09-jvmci-20.3-b18)","opc-request-id":"2D9C43A6BB6B4877B99815B2473F4EF9/9A2041CD15858998DC08E537EDC037CA/D1489DCC2C91020FA8C9BF2C5C6EE2C8","response.Content-Length":69,"request.Content-Length":1054}
```
Second request: Received 200 in splat

```
{"remoteHost":"x.x.x.x","remoteUser":"","ts":1652316391230,"elapsedTime":5195,"statusCode":200,"userAgent":"Oracle-JavaSDK/2.14.1-preview1-SNAPSHOT (Linux/4.14.35-2047.511.5.7.el7uek.x86_64; Java/1.8.0_301; Java HotSpot(TM) 64-Bit Server VM GraalVM EE 20.3.3/25.301-b09-jvmci-20.3-b18)","opc-request-id":"2D9C43A6BB6B4877B99815B2473F4EF9/B3D329331C0EAE4A6E9A90F8CAB5211D/D3C7909F04D0C08D7B5881D6FEDFABB8","response.Content-Length":1708,"request.Content-Length":1050}
```
