### ISSUE TITLE
Exception in thread "main" java.lang.NoSuchFieldError: TOO_MANY_REQUESTS when creating ObjectStorageClient

### ISSUE THREAD

**Issue by Mzamo** [oracle/oci-java-sdk#420]
**This is an OCI java sdk issue**
AuthenticationDetailsProvider provider = SimpleAuthenticationDetailsProvider.builder()
                    .tenantId(oci_tenant_id)
                    .userId(oci_user_id)
                    .region(Region.AF_JOHANNESBURG_1)
                    .fingerprint(oci_finger_print)
                    .privateKeySupplier((Supplier<InputStream>) privateKeySupplier)
                    .build();
**ObjectStorage ociClient = new ObjectStorageClient(provider);**

From the above I get the below exception when creating **new ObjectStorageClient(provider);**

**Exception in thread "main" java.lang_.NoSuchFieldError Create breakpoints_: **TOO_MANY_REQUESTS**
	at com.oracle.bmc.circuitbreaker.CircuitBreakerConfiguration.<clinit>(CircuitBreakerConfiguration.java:44)
	at com.oracle.bmc.util.CircuitBreakerUtils.<clinit>(CircuitBreakerUtils.java:35)
	at com.oracle.bmc.objectstorage.ObjectStorageClient.<init>(ObjectStorageClient.java:317)
	at com.oracle.bmc.objectstorage.ObjectStorageClient.<init>(ObjectStorageClient.java:224)
	at com.oracle.bmc.objectstorage.ObjectStorageClient.<init>(ObjectStorageClient.java:187)
	at com.oracle.bmc.objectstorage.ObjectStorageClient.<init>(ObjectStorageClient.java:152)
	at com.oracle.bmc.objectstorage.ObjectStorageClient.<init>(ObjectStorageClient.java:124)
	at com.oracle.bmc.objectstorage.ObjectStorageClient.<init>(ObjectStorageClient.java:99)
	at com.oracle.bmc.objectstorage.ObjectStorageClient.<init>(ObjectStorageClient.java:76)
	at com.oracle.bmc.objectstorage.ObjectStorageClient.<init>(ObjectStorageClient.java:62)
        at com.oracle.bmc.objectstorage.ObjectStorageClient.<init>(ObjectStorageClient.java:51)**
	at com.vodacom.oci.services.OCI_GenericUtility.getObjectClient(OCI_GenericUtility.java:137)
	at com.vodacom.oci.services.OCI_GenericUtility.main(OCI_GenericUtility.java:47)

Please help!!!

**Comment by y-chandra** [comment]
@Mzamo - Can you please share the output of `mvn dependency:tree` from the root directory of your project? It seems the dependency `jakarta.ws.rs:jakarta.ws.rs-api` is not pointing to the right version (`2.1.6`) or is being overridden by `javax.ws.rs:javax.ws.rs-api`. To resolve this, only `jakarta.ws.rs:jakarta.ws.rs-api` version `2.1.6` should be included in your project.

**Comment by y-chandra** [comment]
Seems like this was resolved by removing `aws-java-sdk*` dependencies from pom.xml as mentioned [here](https://stackoverflow.com/questions/73007996/i-am-getting-exception-in-thread-main-java-lang-nosuchfielderror-too-many-r/73027138?noredirect=1#comment128993494_73027138) 
Closing this issue for now, please feel free to reopen if the issue persists
