### ISSUE TITLE
java.lang.NoClassDefFoundError: org/glassfish/jersey/internal/FeatureConfigurator

### ISSUE THREAD

**Issue by pallabrath** [oracle/oci-java-sdk#422]
InstancePrincipalsAuthenticationDetailsProvider.builder().build() is resulting java.lang.NoClassDefFoundError: org/glassfish/jersey/internal/FeatureConfigurator error. I am using 2.36.1 version in a dropwizard app. And oke is the runtime env.
=======================
<dependency>
            <groupId>com.oracle.oci.sdk</groupId>
            <artifactId>oci-java-sdk-common</artifactId>
            <version>2.36.1</version>
        </dependency>
        <dependency>
            <groupId>com.oracle.oci.sdk</groupId>
            <artifactId>oci-java-sdk-objectstorage</artifactId>
            <version>2.36.1</version>
        </dependency>
        <dependency>
            <groupId>com.oracle.oci.sdk</groupId>
            <artifactId>oci-java-sdk-loggingingestion</artifactId>
            <version>2.36.1</version>
        </dependency>
        <dependency>
            <groupId>com.oracle.oci.sdk</groupId>
            <artifactId>oci-java-sdk-identity</artifactId>
            <version>2.36.1</version>
        </dependency>

Stack trace
=========
ERROR [2022-07-22 11:49:57,354] io.dropwizard.jersey.errors.LoggingExceptionMapper: Error handling a request: 8bc7122825ccc339
! java.lang.ClassNotFoundException: org.glassfish.jersey.internal.FeatureConfigurator
! at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
! at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
! at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
! at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
! ... 84 common frames omitted
! Causing: java.lang.NoClassDefFoundError: org/glassfish/jersey/internal/FeatureConfigurator
! at org.glassfish.jersey.client.ClientConfig$State.initRuntime(ClientConfig.java:422)
! at org.glassfish.jersey.internal.util.collection.Values$LazyValueImpl.get(Values.java:317)
! at org.glassfish.jersey.client.ClientConfig.getRuntime(ClientConfig.java:820)
! at org.glassfish.jersey.client.ClientRequest.getClientRuntime(ClientRequest.java:176)
! at org.glassfish.jersey.client.ClientRequest.getInjectionManager(ClientRequest.java:567)
! at org.glassfish.jersey.client.JerseyWebTarget.onBuilder(JerseyWebTarget.java:371)
! at org.glassfish.jersey.client.JerseyWebTarget.request(JerseyWebTarget.java:206)
! at org.glassfish.jersey.client.JerseyWebTarget.request(JerseyWebTarget.java:38)
! at com.oracle.bmc.auth.AbstractFederationClientAuthenticationDetailsProviderBuilder.lambda$executeInstanceFallback$1(AbstractFederationClientAuthenticationDetailsProviderBuilder.java:346)
! at com.oracle.bmc.internal.GuavaUtils.lambda$adaptFromGuava$0(GuavaUtils.java:18)
! at com.oracle.bmc.auth.AbstractFederationClientAuthenticationDetailsProviderBuilder.simpleRetry(AbstractFederationClientAuthenticationDetailsProviderBuilder.java:503)
! at com.oracle.bmc.auth.AbstractFederationClientAuthenticationDetailsProviderBuilder.simpleRetry(AbstractFederationClientAuthenticationDetailsProviderBuilder.java:490)
! at com.oracle.bmc.auth.AbstractFederationClientAuthenticationDetailsProviderBuilder.executeInstanceFallback(AbstractFederationClientAuthenticationDetailsProviderBuilder.java:342)
! at com.oracle.bmc.auth.AbstractFederationClientAuthenticationDetailsProviderBuilder.autoDetectEndpointUsingMetadataUrl(AbstractFederationClientAuthenticationDetailsProviderBuilder.java:249)
! at com.oracle.bmc.auth.AbstractFederationClientAuthenticationDetailsProviderBuilder.autoDetectUsingMetadataUrl(AbstractFederationClientAuthenticationDetailsProviderBuilder.java:237)
! at com.oracle.bmc.auth.InstancePrincipalsAuthenticationDetailsProvider$InstancePrincipalsAuthenticationDetailsProviderBuilder.build(InstancePrincipalsAuthenticationDetailsProvider.java:99)
! at com.oracle.adbd.manager.IdentityMgr.<init>(IdentityMgr.java:16)

**Comment by pallabrath** [comment]
adding dropwizard-jersey dependency solved the error
```
<dependency>
            <groupId>io.dropwizard</groupId>
            <artifactId>dropwizard-jersey</artifactId>
            <version>2.1.0</version>
 </dependency>
```
