### ISSUE TITLE
Error Uploading file to OCI object Storage

### ISSUE THREAD

**Issue by suneetp07** [oracle/oci-java-sdk#576]
Hi,
I am getting this error uploading file to object storage from Spring boot.
I used this example.
https://medium.com/@rashidrizvi/how-to-upload-files-to-oci-object-storage-using-java-spring-boot-1941235f53b8

org.glassfish.hk2.api.MultiException: A MultiException has 1 exceptions.  They are:
1. org.glassfish.hk2.api.UnsatisfiedDependencyException: There was no object available for injection at SystemInjecteeImpl(requiredType=int,parent=DaemonClientAsyncExecutorProvider,qualifiers={@javax.inject.Named("ClientAsyncThreadPoolSize")},position=0,optional=false,self=false,unqualified=null,2072183845)

	at org.jvnet.hk2.internal.ThreeThirtyResolver.resolve(ThreeThirtyResolver.java:51)
	at org.jvnet.hk2.internal.Utilities.justCreate(Utilities.java:1055)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.create(ServiceLocatorImpl.java:968)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.createAndInitialize(ServiceLocatorImpl.java:1072)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.createAndInitialize(ServiceLocatorImpl.java:1064)
	at org.glassfish.jersey.inject.hk2.AbstractHk2InjectionManager.createAndInitialize(AbstractHk2InjectionManager.java:189)
	at org.glassfish.jersey.inject.hk2.ImmediateHk2InjectionManager.createAndInitialize(ImmediateHk2InjectionManager.java:30)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1689)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:310)
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.glassfish.jersey.process.internal.AbstractExecutorProvidersConfigurator.registerExecutors(AbstractExecutorProvidersConfigurator.java:65)
	at org.glassfish.jersey.client.ClientExecutorProvidersConfigurator.init(ClientExecutorProvidersConfigurator.java:139)
	at org.glassfish.jersey.client.ClientConfig$State.initRuntime(ClientConfig.java:452)
	at org.glassfish.jersey.internal.util.collection.Values$LazyValueImpl.get(Values.java:317)
	at org.glassfish.jersey.client.ClientConfig.getRuntime(ClientConfig.java:814)
	at org.glassfish.jersey.client.ClientRequest.getConfiguration(ClientRequest.java:263)
	at org.glassfish.jersey.client.JerseyInvocation.validateHttpMethodAndEntity(JerseyInvocation.java:121)
	at org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:90)
	at org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:86)
	at org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:77)
	at org.glassfish.jersey.client.JerseyInvocation$AsyncInvoker.method(JerseyInvocation.java:578)
	at org.glassfish.jersey.client.JerseyCompletionStageRxInvoker.method(JerseyCompletionStageRxInvoker.java:31)
	at com.oracle.bmc.http.client.jersey.JerseyHttpRequest.execute(JerseyHttpRequest.java:239)
	at com.oracle.bmc.http.internal.ClientCall.callAsyncImpl(ClientCall.java:959)
	at com.oracle.bmc.http.internal.ClientCall.callAsyncTokenRefresh(ClientCall.java:902)
	at com.oracle.bmc.retrier.BmcGenericRetrier.doFunctionCall(BmcGenericRetrier.java:175)
	at com.oracle.bmc.retrier.BmcGenericRetrier.doFunctionCallAsync(BmcGenericRetrier.java:181)
	at com.oracle.bmc.retrier.BmcGenericRetrier.lambda$executeAsync$3(BmcGenericRetrier.java:119)
	at com.oracle.bmc.waiter.GenericWaiter.executeAsync(GenericWaiter.java:109)
	at com.oracle.bmc.waiter.GenericWaiter.executeAsync(GenericWaiter.java:98)
	at com.oracle.bmc.retrier.BmcGenericRetrier.executeAsync(BmcGenericRetrier.java:112)
	at com.oracle.bmc.http.internal.ClientCall.callAsyncWithRetrier(ClientCall.java:892)
	at com.oracle.bmc.http.internal.ClientCall.callAsync0(ClientCall.java:839)
	at com.oracle.bmc.http.internal.ClientCall.callSync(ClientCall.java:1032)
	at com.oracle.bmc.objectstorage.ObjectStorageClient.putObject(ObjectStorageClient.java:1745)

**Comment by suneetp07** [comment]
Finally go it to work. Used Shaded jar.

	implementation group: 'com.oracle.oci.sdk', name: 'oci-java-sdk-shaded-full', version: '3.10.0'

**Comment by bhagwatvyas** [comment]
@suneetp07 I'll close this issue, please feel free to reopen if you need more assistance
