### ISSUE TITLE
Error returned by GetSecretBundle operation in Secrets service.(-1, null, false) Unknown error - when running my service image from OCI Container Instance

### ISSUE THREAD

**Issue by srengach** [oracle/oci-java-sdk#588]
Error returned by GetSecretBundle operation in Secrets service.(-1, null, false) Unknown error\nTimestamp: 2024-04-04T19:55:28.414Z\nClient version: Oracle-JavaSDK/3.19.0\nRequest Endpoint: https://secrets.vaults.us-phoenix-1.oci.oraclecloud.com/20190301/secretbundles/ocid1.vaultsecret.oc1.phx.amaaaaaacyceeqiagsc4lbmurh44vbkgzoengzlmm2nffcug75kcn5zpwf4q?stage\u003dCURRENT\nTroubleshooting Tips: See https://docs.oracle.com/en-us/iaas/Content/API/References/apierrors.htm#apierrors_-1__-1_ for more information about resolving this error\nAlso see https://docs.oracle.com/iaas/api/#/en/secretretrieval/20190301/SecretBundle/GetSecretBundle for details on this operation\u0027s requirements.\nTo get more info on the failing request, you can enable debug level logs as mentioned in `Using SLF4J for Logging section` in https://docs.oracle.com/en-us/iaas/Content/API/SDKDocs/javasdkconfig.htm.\nIf you are unable to resolve this Secrets issue, please contact Oracle support and provide them this full error message."

**Comment by srengach** [comment]
Stack TRACE
2024-04-05T13:32:39.729657665Z stdout F javax.ws.rs.ProcessingException: Error reading entity from input stream.
2024-04-05T13:32:39.729659909Z stdout F 	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:900)
2024-04-05T13:32:39.729661441Z stdout F 	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:845)
2024-04-05T13:32:39.729663075Z stdout F 	at org.glassfish.jersey.client.ClientResponse.readEntity(ClientResponse.java:340)
2024-04-05T13:32:39.729664427Z stdout F 	at org.glassfish.jersey.client.InboundJaxrsResponse$2.call(InboundJaxrsResponse.java:104)
2024-04-05T13:32:39.729665779Z stdout F 	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
2024-04-05T13:32:39.729667392Z stdout F 	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
2024-04-05T13:32:39.729668795Z stdout F 	at org.glassfish.jersey.internal.Errors.process(Errors.java:205)
2024-04-05T13:32:39.729670077Z stdout F 	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:365)
2024-04-05T13:32:39.729671491Z stdout F 	at org.glassfish.jersey.client.InboundJaxrsResponse.runInScopeIfPossible(InboundJaxrsResponse.java:244)
2024-04-05T13:32:39.729695114Z stdout F 	at org.glassfish.jersey.client.InboundJaxrsResponse.readEntity(InboundJaxrsResponse.java:101)
2024-04-05T13:32:39.729696968Z stdout F 	at com.oracle.bmc.http.client.jersey.JerseyHttpResponse.readEntitySync(JerseyHttpResponse.java:129)
2024-04-05T13:32:39.729698341Z stdout F 	at com.oracle.bmc.http.client.jersey.JerseyHttpResponse.body(JerseyHttpResponse.java:105)
2024-04-05T13:32:39.729699673Z stdout F 	at com.oracle.bmc.http.internal.ClientCall.transformResponse(ClientCall.java:693)
2024-04-05T13:32:39.729701136Z stdout F 	at com.oracle.bmc.http.internal.ClientCall.lambda$callAsyncImpl$22(ClientCall.java:974)
2024-04-05T13:32:39.729702539Z stdout F 	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
2024-04-05T13:32:39.729703852Z stdout F 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
2024-04-05T13:32:39.729705195Z stdout F 	at com.oracle.bmc.http.internal.SyncFutureWaiter$Waiter.waitAndWork(SyncFutureWaiter.java:63)
2024-04-05T13:32:39.729706657Z stdout F 	at com.oracle.bmc.http.internal.SyncFutureWaiter.listenForResult(SyncFutureWaiter.java:32)
2024-04-05T13:32:39.72970797Z stdout F 	at com.oracle.bmc.http.internal.ClientCall.callSync(ClientCall.java:1032)
2024-04-05T13:32:39.729709342Z stdout F 	at com.oracle.bmc.secrets.SecretsClient.getSecretBundle(SecretsClient.java:117)
2024-04-05T13:32:39.729711446Z stdout F 	at com.kaiser.filehandler.service.OCIVaultSecretsClientService.getSecretValue(OCIVaultSecretsClientService.java:27)
2024-04-05T13:32:39.729712929Z stdout F 	at com.kaiser.filehandler.service.AsyncFileEncryptionService.doEncryptAndTransfer(AsyncFileEncryptionService.java:148)
2024-04-05T13:32:39.729717126Z stdout F 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2024-04-05T13:32:39.729718559Z stdout F 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
2024-04-05T13:32:39.729719902Z stdout F 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2024-04-05T13:32:39.729721395Z stdout F 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2024-04-05T13:32:39.729722777Z stdout F 	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
2024-04-05T13:32:39.72972411Z stdout F 	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
2024-04-05T13:32:39.729725452Z stdout F 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
2024-04-05T13:32:39.729726885Z stdout F 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:756)
2024-04-05T13:32:39.729728298Z stdout F 	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
2024-04-05T13:32:39.7297297Z stdout F 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2024-04-05T13:32:39.729731063Z stdout F 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
2024-04-05T13:32:39.729732425Z stdout F 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2024-04-05T13:32:39.729733758Z stdout F 	at java.base/java.lang.Thread.run(Thread.java:831)
2024-04-05T13:32:39.729735451Z stdout F Caused by: com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `com.oracle.bmc.secrets.model.SecretBundle$Stages` from String "CURRENT": not one of the values accepted for Enum class: [Deprecated, UnknownEnumValue, Previous, Current, Latest, Pending]
2024-04-05T13:32:39.729737034Z stdout F  at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 1, column: 4876] (through reference chain: com.oracle.bmc.secrets.model.SecretBundle["stages"]->java.util.ArrayList[0])
2024-04-05T13:32:39.729741442Z stdout F 	at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:67)
2024-04-05T13:32:39.729743035Z stdout F 	at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:1991)
2024-04-05T13:32:39.729744418Z stdout F 	at com.fasterxml.jackson.databind.DeserializationContext.handleWeirdStringValue(DeserializationContext.java:1219)
2024-04-05T13:32:39.729745751Z stdout F 	at com.fasterxml.jackson.databind.deser.std.EnumDeserializer._deserializeAltString(EnumDeserializer.java:356)
2024-04-05T13:32:39.729747054Z stdout F 	at com.fasterxml.jackson.databind.deser.std.EnumDeserializer._fromString(EnumDeserializer.java:230)
2024-04-05T13:32:39.729748407Z stdout F 	at com.fasterxml.jackson.databind.deser.std.EnumDeserializer.deserialize(EnumDeserializer.java:198)
2024-04-05T13:32:39.729749759Z stdout F 	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:355)
2024-04-05T13:32:39.729751092Z stdout F 	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
2024-04-05T13:32:39.729752404Z stdout F 	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
2024-04-05T13:32:39.729762914Z stdout F 	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:542)
2024-04-05T13:32:39.729764517Z stdout F 	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:564)
2024-04-05T13:32:39.729765889Z stdout F 	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:439)
2024-04-05T13:32:39.729768775Z stdout F 	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1405)
2024-04-05T13:32:39.729770227Z stdout F 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:352)
2024-04-05T13:32:39.729772832Z stdout F 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185)
2024-04-05T13:32:39.729774265Z stdout F 	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
2024-04-05T13:32:39.729775898Z stdout F 	at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:2025)
2024-04-05T13:32:39.72977724Z stdout F 	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1175)
2024-04-05T13:32:39.729778603Z stdout F 	at org.glassfish.jersey.jackson.internal.jackson.jaxrs.base.ProviderBase.readFrom(ProviderBase.java:837)
2024-04-05T13:32:39.729779956Z stdout F 	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.invokeReadFrom(ReaderInterceptorExecutor.java:233)
2024-04-05T13:32:39.729781398Z stdout F 	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.aroundReadFrom(ReaderInterceptorExecutor.java:212)
2024-04-05T13:32:39.729782741Z stdout F 	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:132)
2024-04-05T13:32:39.729784073Z stdout F 	at org.glassfish.jersey.message.internal.MessageBodyFactory.readFrom(MessageBodyFactory.java:1072)
2024-04-05T13:32:39.729785486Z stdout F 	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:885)
2024-04-05T13:32:39.729786969Z stdout F 	... 34 common frames omitted
