### ISSUE TITLE
InstancePrincipalsAuthenticationDetailsProviderExample

### ISSUE THREAD

**Issue by buffaloforge** [oracle/oci-java-sdk#61]
I seem to be able to run the other examples fine, however this one throws the below error regarding a time out?  If it was a firewall issue, it would seem that the other examples would time out, however they run fine.  ie. GetInstancePublicIpExample works fine.  Any thoughts would be appreciated
thanks

Exception in thread "main" javax.ws.rs.ProcessingException: java.net.ConnectException: Connection timed out: connect
	at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:287)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:252)
	at org.glassfish.jersey.client.JerseyInvocation$2.call(JerseyInvocation.java:701)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:697)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:420)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:316)
	at com.oracle.bmc.auth.InstancePrincipalsAuthenticationDetailsProvider$InstancePrincipalsAuthenticationDetailsProviderBuilder.build(InstancePrincipalsAuthenticationDetailsProvider.java:114)
	at InstancePrincipalsAuthenticationDetailsProviderExample.main(InstancePrincipalsAuthenticationDetailsProviderExample.java:22)
Caused by: java.net.ConnectException: Connection timed out: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at sun.net.NetworkClient.doConnect(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.<init>(Unknown Source)
	at sun.net.www.http.HttpClient.New(Unknown Source)
	at sun.net.www.http.HttpClient.New(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.HttpURLConnection.getResponseCode(Unknown Source)
	at org.glassfish.jersey.client.internal.HttpUrlConnector._apply(HttpUrlConnector.java:399)
	at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:285)
	... 11 more

**Comment by jodoglevy** [comment]
To expand on what Bentham said, we'll update this example to make it more clear that this exception is due to the example not being run on an OCI instance.

**Comment by buffaloforge** [comment]
I guess maybe im confused, I am running this example against an oracle compute node.  Do you mean the code has to be run directly on the compute node, and cannot be run remotely?

**Comment by jodoglevy** [comment]
Yes. Please see https://docs.us-phoenix-1.oraclecloud.com/Content/Identity/Tasks/callingservicesfrominstances.htm for more details.

**Comment by pablojhernandezf** [comment]
Having a similar issue while implementing what @jodoglevy  mentions , while using the code in https://docs.cloud.oracle.com/iaas/Content/Identity/Tasks/callingservicesfrominstances.htm#ConfiguringtheSDKCLIorTerraform 

Here's the traceback

Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.lang.NoSuchFieldError: EXCLUDE_EMPTY
	at org.glassfish.jersey.client.ClientConfig$State.<init>(ClientConfig.java:147)
	at org.glassfish.jersey.client.ClientConfig.<init>(ClientConfig.java:457)
	at org.glassfish.jersey.client.JerseyClientBuilder.<init>(JerseyClientBuilder.java:94)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at javax.ws.rs.client.FactoryFinder.newInstance(FactoryFinder.java:116)
	at javax.ws.rs.client.FactoryFinder.find(FactoryFinder.java:206)
	at javax.ws.rs.client.ClientBuilder.newBuilder(ClientBuilder.java:86)
	at javax.ws.rs.client.ClientBuilder.newClient(ClientBuilder.java:114)
	at com.oracle.bmc.auth.AbstractFederationClientAuthenticationDetailsProviderBuilder.autoDetectEndpointUsingMetadataUrl(AbstractFederationClientAuthenticationDetailsProviderBuilder.java:151)
	at com.oracle.bmc.auth.AbstractFederationClientAuthenticationDetailsProviderBuilder.autoDetectUsingMetadataUrl(AbstractFederationClientAuthenticationDetailsProviderBuilder.java:140)
	at com.oracle.bmc.auth.InstancePrincipalsAuthenticationDetailsProvider$InstancePrincipalsAuthenticationDetailsProviderBuilder.build(InstancePrincipalsAuthenticationDetailsProvider.java:76)

The line of code that produces the error is:
InstancePrincipalsAuthenticationDetailsProvider provider = 
                              InstancePrincipalsAuthenticationDetailsProvider.builder().build();
And the machine where this code is  executed is an OCI instance (trying to access a remote Object Storage)

Thanks in advance

**Comment by andy-miles** [comment]
Which version of Jersey and Jackson are included in your application's classpath?  

This type of exception (java.lang.NoSuchFieldError: EXCLUDE_EMPTY) is typically caused by a version mismatch of the Jersey client libraries.  The OCI Java SDK uses version 2.27 of the Jersey client library and version 2.9.8 of Jackson found [here](https://github.com/oracle/oci-java-sdk/blob/master/pom.xml#L27).

If you continue to experience issues after verifying the libraries included in your application's classpath, please open a new GitHub issue.
