### ISSUE TITLE
 java.lang.IllegalArgumentException: Cannot redefine service OBJECTSTORAGE

### ISSUE THREAD

**Issue by shravan88k** [oracle/oci-java-sdk#614]
`bmc-objectstorage/bmc-objectstorage-generated/src/main/java/com/oracle/bmc/objectstorage/ObjectStorageClient.java`

We are extending ObjectStorageClient class, for our Flink Service connection to ObjectStorage.

`public class CustomObjectStorageClient extends ObjectStorageClient {
    
    public CustomObjectStorageClient(Configuration conf) throws Exception {
        super(getAuthProvider(conf), getClientConfiguration(conf));
    }`

Since we upgraded our java-sdk (2.52.1 to 2.72.0) and hdfs-connector (3.3.4.0.1.1 to 3.3.4.1.0.0) versions we are seeing below error.

`2024-07-15 18:13:04.269 [main] INFO  org.apache.flink.runtime.entrypoint.ClusterEntrypoint  - Shutting StandaloneSessionClusterEntrypoint down with application status FAILED. Diagnostics com.google.common.util.concurrent.ExecutionError: java.lang.ExceptionInInitializerError
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2084)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4012)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4035)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5011)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5018)
	at com.oracle.bmc.hdfs.BmcFilesystem.initialize(BmcFilesystem.java:174)
	at org.apache.flink.runtime.fs.hdfs.HadoopFsFactory.create(HadoopFsFactory.java:168)
	at org.apache.flink.core.fs.FileSystem.getUnguardedFileSystem(FileSystem.java:526)
	at org.apache.flink.core.fs.FileSystem.get(FileSystem.java:409)
	at org.apache.flink.core.fs.Path.getFileSystem(Path.java:274)
	at org.apache.flink.runtime.blob.BlobUtils.createFileSystemBlobStore(BlobUtils.java:99)
	at org.apache.flink.runtime.blob.BlobUtils.createBlobStoreFromConfig(BlobUtils.java:86)
	at org.apache.flink.runtime.highavailability.HighAvailabilityServicesUtils.createZooKeeperHaServices(HighAvailabilityServicesUtils.java:89)
	at org.apache.flink.runtime.highavailability.HighAvailabilityServicesUtils.createHighAvailabilityServices(HighAvailabilityServicesUtils.java:133)
	at org.apache.flink.runtime.entrypoint.ClusterEntrypoint.createHaServices(ClusterEntrypoint.java:449)
	at org.apache.flink.runtime.entrypoint.ClusterEntrypoint.initializeServices(ClusterEntrypoint.java:397)
	at org.apache.flink.runtime.entrypoint.ClusterEntrypoint.runCluster(ClusterEntrypoint.java:287)
	at org.apache.flink.runtime.entrypoint.ClusterEntrypoint.lambda$startCluster$1(ClusterEntrypoint.java:237)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1899)
	at org.apache.flink.runtime.security.contexts.HadoopSecurityContext.runSecured(HadoopSecurityContext.java:41)
	at org.apache.flink.runtime.entrypoint.ClusterEntrypoint.startCluster(ClusterEntrypoint.java:234)
	at org.apache.flink.runtime.entrypoint.ClusterEntrypoint.runClusterEntrypoint(ClusterEntrypoint.java:739)
	at org.apache.flink.runtime.entrypoint.StandaloneSessionClusterEntrypoint.main(StandaloneSessionClusterEntrypoint.java:59)
Caused by: java.lang.ExceptionInInitializerError
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.oracle.bmc.hdfs.store.BmcDataStoreFactory.createClass(BmcDataStoreFactory.java:432)
	at com.oracle.bmc.hdfs.store.BmcDataStoreFactory.createClient(BmcDataStoreFactory.java:111)
	at com.oracle.bmc.hdfs.store.BmcDataStoreFactory.createDataStore(BmcDataStoreFactory.java:99)
	at com.oracle.bmc.hdfs.BmcFilesystemImpl.initialize(BmcFilesystem.java:413)
	at com.oracle.bmc.hdfs.BmcFilesystem$1.load(BmcFilesystem.java:109)
	at com.oracle.bmc.hdfs.BmcFilesystem$1.load(BmcFilesystem.java:104)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3571)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2313)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2190)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2080)
	... 24 more
Caused by: java.lang.IllegalArgumentException: Cannot redefine service 'OBJECTSTORAGE'. Existing: 'Services.BasicService(serviceName=OBJECTSTORAGE, serviceEndpointPrefix=objectstorage, serviceEndpointTemplate=https://objectstorage/.{region}.{secondLevelDomain}, endpointServiceName=null)', New: 'Services.BasicService(serviceName=OBJECTSTORAGE, serviceEndpointPrefix=objectstorage, serviceEndpointTemplate=https://objectstorage/.{region}.{secondLevelDomain}, endpointServiceName=objectstorage)'
	at com.oracle.bmc.Services.create(Services.java:73)
	at com.oracle.bmc.Services.access$100(Services.java:21)
	at com.oracle.bmc.Services$ServiceBuilder.build(Services.java:234)
	at com.oracle.bmc.objectstorage.ObjectStorageClient.<clinit>(ObjectStorageClient.java:27)
	... 36 more
.
2024-07-15 18:13:04.275 [main] INFO  org.apache.flink.runtime.rpc.pekko.PekkoRpcService  - Stopping Pekko RPC service`

**Comment by shravan88k** [comment]
Upgraded hdfs-connector to '3.3.4.1.0.0' to resolve the issue.
