### ISSUE TITLE
Error message from Java SDK is misleading

### ISSUE THREAD

**Issue by ariel777** [oracle/oci-java-sdk#62]
Tag map accepts <String, Object>: 
```
com.oracle.bmc.core.model.LaunchInstanceDetails.Builder#definedTags(
                java.util.Map<String, java.util.Map<String, Object>> definedTags)
```

I passed 1 tag value as an integer and got:
`com.oracle.bmc.model.BmcException: (404, NotAuthorizedOrNotFound, false) Authorization failed or requested resource not found.
`
Changed value to String - works fine... 

Issue: the message is completely misleading, it took a time to find what was the reason for the issue.

P.S.: "NotAuthorizedOrNotFound" is not good as well - better to have them separate: "NotAuthorized" and "NotFound".

More details about exception:
```
com.oracle.bmc.model.BmcException: (404, NotAuthorizedOrNotFound, false) Authorization failed or requested resource not found. (opc-request-id: 5913A750FC354B8FB23E19B0CE5C0B1C/2096C162CA9B27B6846C72E16289F895/DFB7CCCE5538D47AADC5A07D3A8CCBAA)
	at com.oracle.bmc.http.internal.ResponseHelper.throwIfNotSuccessful(ResponseHelper.java:92)
	at com.oracle.bmc.http.internal.ResponseConversionFunctionFactory$ValidatingParseResponseFunction.apply(ResponseConversionFunctionFactory.java:86)
	at com.oracle.bmc.http.internal.ResponseConversionFunctionFactory$ValidatingParseResponseFunction.apply(ResponseConversionFunctionFactory.java:82)
	at com.oracle.bmc.core.internal.http.LaunchInstanceConverter$1.apply(LaunchInstanceConverter.java:59)
	at com.oracle.bmc.core.internal.http.LaunchInstanceConverter$1.apply(LaunchInstanceConverter.java:47)
	at com.oracle.bmc.core.ComputeClient.launchInstance(ComputeClient.java:916)
```

**Comment by benthamc** [comment]
Thanks for reporting this, we will consider improving the error message in the future release.
