### ISSUE TITLE
Unrecognized field "id" (AvailabilityDomain) with oci-java-sdk-full-shaded-1.2.44.jar

### ISSUE THREAD

**Issue by shihchang** [oracle/oci-java-sdk#79]
I accidentally replace oci-java-sdk-full-1.2.44.jar to the shadded jar oci-java-sdk-full-shaded-1.2.44.jar in the classpath and got the following exception. The call on IdentityClient.listAvailabilityDomains is from Spinnaker/clouddriver-oracle.

javax.ws.rs.ProcessingException: Error reading entity from input stream.
        at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:889) ~[jersey-common-2.25.1.jar:na]
        at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:834) ~[jersey-common-2.25.1.jar:na]
        at org.glassfish.jersey.client.ClientResponse.readEntity(ClientResponse.java:368) ~[jersey-client-2.25.1.jar:na]
        at org.glassfish.jersey.client.InboundJaxrsResponse$2.call(InboundJaxrsResponse.java:126) ~[jersey-client-2.25.1.jar:na]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315) ~[jersey-common-2.25.1.jar:na]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297) ~[jersey-common-2.25.1.jar:na]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:228) ~[jersey-common-2.25.1.jar:na]
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:419) ~[jersey-common-2.25.1.jar:na]
        at org.glassfish.jersey.client.InboundJaxrsResponse.runInScopeIfPossible(InboundJaxrsResponse.java:267) ~[jersey-client-2.25.1.jar:na]
        at org.glassfish.jersey.client.InboundJaxrsResponse.readEntity(InboundJaxrsResponse.java:123) ~[jersey-client-2.25.1.jar:na]
        at com.oracle.bmc.http.internal.ResponseHelper.readEntity(ResponseHelper.java:128) ~[oci-java-sdk-full-shaded-1.2.44.jar:na]
        at com.oracle.bmc.http.internal.ResponseConversionFunctionFactory$ParseGenericResponseWithHeadersFunction.doApply(ResponseConversionFunctionFactory.java:69) ~[oci-java-sdk-full-shaded-1.2.44.jar:na]
        at com.oracle.bmc.http.internal.ResponseConversionFunctionFactory$ParseGenericResponseWithHeadersFunction.doApply(ResponseConversionFunctionFactory.java:62) ~[oci-java-sdk-full-shaded-1.2.44.jar:na]
        at com.oracle.bmc.http.internal.ResponseConversionFunctionFactory$ValidatingParseResponseFunction.apply(ResponseConversionFunctionFactory.java:87) ~[oci-java-sdk-full-shaded-1.2.44.jar:na]
        at com.oracle.bmc.http.internal.ResponseConversionFunctionFactory$ValidatingParseResponseFunction.apply(ResponseConversionFunctionFactory.java:82) ~[oci-java-sdk-full-shaded-1.2.44.jar:na]
        at com.oracle.bmc.identity.internal.http.ListAvailabilityDomainsConverter$1.apply(ListAvailabilityDomainsConverter.java:71) ~[oci-java-sdk-full-shaded-1.2.44.jar:na]
        at com.oracle.bmc.identity.internal.http.ListAvailabilityDomainsConverter$1.apply(ListAvailabilityDomainsConverter.java:53) ~[oci-java-sdk-full-shaded-1.2.44.jar:na]
        at com.oracle.bmc.identity.IdentityClient.listAvailabilityDomains(IdentityClient.java:1349) ~[oci-java-sdk-full-shaded-1.2.44.jar:na]
        ...
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "id" (class com.oracle.bmc.identity.model.AvailabilityDomain), not marked as ignorable (3 known properties: "__explicitlySet__", "name", "compartmentId"])
 at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 5, column: 2] (through reference chain: java.util.ArrayList[0]->com.oracle.bmc.identity.model.AvailabilityDomain["id"])
        at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:60) ~[jackson-databind-2.9.2.jar:2.9.2]
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:822) ~[jackson-databind-2.9.2.jar:2.9.2]
        at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1152) ~[jackson-databind-2.9.2.jar:2.9.2]
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1567) ~[jackson-databind-2.9.2.jar:2.9.2]
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperties(BeanDeserializerBase.java:1521) ~[jackson-databind-2.9.2.jar:2.9.2]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:437) ~[jackson-databind-2.9.2.jar:2.9.2]
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1265) ~[jackson-databind-2.9.2.jar:2.9.2]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:325) ~[jackson-databind-2.9.2.jar:2.9.2]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159) ~[jackson-databind-2.9.2.jar:2.9.2]
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:285) ~[jackson-databind-2.9.2.jar:2.9.2]
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244) ~[jackson-databind-2.9.2.jar:2.9.2]
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27) ~[jackson-databind-2.9.2.jar:2.9.2]
        at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:1571) ~[jackson-databind-2.9.2.jar:2.9.2]
        at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:965) ~[jackson-databind-2.9.2.jar:2.9.2]
        at com.fasterxml.jackson.jaxrs.base.ProviderBase.readFrom(ProviderBase.java:815) ~[jackson-jaxrs-base-2.9.2.jar:2.9.2]
        at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.invokeReadFrom(ReaderInterceptorExecutor.java:256) ~[jersey-common-2.25.1.jar:na]
        at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.aroundReadFrom(ReaderInterceptorExecutor.java:235) ~[jersey-common-2.25.1.jar:na]
        at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:155) ~[jersey-common-2.25.1.jar:na]
        at org.glassfish.jersey.message.internal.MessageBodyFactory.readFrom(MessageBodyFactory.java:1085) ~[jersey-common-2.25.1.jar:na]
        at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:874) ~[jersey-common-2.25.1.jar:na]
        ... 174 common frames omitted

**Comment by shihchang** [comment]
I suspect the jersey client is using the original/unshaded jackson which does not understand the shaded jackson annotations on the model classes.

**Comment by sumitkdey** [comment]
Hello @shihchang,
Could you please provide a sample that runs into this issue? I used the following maven dependency

    <dependency>
      <groupId>com.oracle.oci.sdk</groupId>
      <artifactId>oci-java-sdk-shaded-full</artifactId>
      <version>1.2.44</version>
    </dependency>

and the code snippet below but was unable to repro this.

        final ConfigFileReader.ConfigFile configFile =
                ConfigFileReader.parse(CONFIG_LOCATION, CONFIG_PROFILE);
        final AuthenticationDetailsProvider authenticationDetailsProvider =
                new ConfigFileAuthenticationDetailsProvider(configFile);

        final IdentityClient identityClient = new IdentityClient(authenticationDetailsProvider);
        identityClient.setRegion(Region.US_PHOENIX_1);

        ListAvailabilityDomainsResponse listAvailabilityDomainsResponse =
                identityClient.listAvailabilityDomains(
                        ListAvailabilityDomainsRequest.builder()
                                .compartmentId("<redacted>")
                                .build());
        System.out.println(listAvailabilityDomainsResponse.getItems());

**Comment by ROMMIEOZEE** [comment]
You can use java to check wheather there is an error or not

**Comment by sumitkdey** [comment]
@shihchang, Please let us know if you are still running into this issue.

**Comment by shihchang** [comment]
Closed as I do not have the environment to reproduce it for now.
