### ISSUE TITLE
UploadManager.upload throw java.io.IOException: too many bytes written

### ISSUE THREAD

**Issue by ekumen** [oracle/oci-java-sdk#82]
Hi,
I use UploadManager to upload file to objectstorage. The to be uploaded file may be appended more content meanwhile. I get below exception sometimes. I'm using OCI 1.2.41 JAVA SDK. Thanks for your help!

StackTrace:
com.oracle.bmc.model.BmcException: (-1, null, false) Processing exception while communicating to: https://objectstorage.us-ashburn-1.oraclecloud.com (outbound opc-request-id: B25D26E08AF64A49806539373307FDE0)
        at com.oracle.bmc.http.internal.RestClient.convertToBmcException(RestClient.java:537)
        at com.oracle.bmc.http.internal.RestClient.put(RestClient.java:354)
        at com.oracle.bmc.objectstorage.ObjectStorageClient.putObject(ObjectStorageClient.java:829)
        at com.oracle.bmc.objectstorage.transfer.internal.SimpleRetry$1.apply(SimpleRetry.java:34)
        at com.oracle.bmc.objectstorage.transfer.internal.SimpleRetry$1.apply(SimpleRetry.java:26)
        at com.oracle.bmc.objectstorage.transfer.UploadManager.singleUpload(UploadManager.java:96)
        at com.oracle.bmc.objectstorage.transfer.UploadManager.upload(UploadManager.java:73)
        ....
Caused by: javax.ws.rs.ProcessingException: java.io.IOException: too many bytes written
        at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:287)
        at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:252)
        at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:684)
        at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:681)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
        at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:681)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:437)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.put(JerseyInvocation.java:326)
        at com.oracle.bmc.http.internal.ForwardingInvocationBuilder.put(ForwardingInvocationBuilder.java:134)
        at com.oracle.bmc.http.internal.RestClient.put(RestClient.java:351)
        ... 20 more
Caused by: java.io.IOException: too many bytes written
        at sun.net.www.protocol.http.HttpURLConnection$StreamingOutputStream.write(HttpURLConnection.java:3523)
        at org.glassfish.jersey.message.internal.CommittingOutputStream.write(CommittingOutputStream.java:229)
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$UnCloseableOutputStream.write(WriterInterceptorExecutor.java:299)
        at org.glassfish.jersey.message.internal.ReaderWriter.writeTo(ReaderWriter.java:116)
        at org.glassfish.jersey.message.internal.AbstractMessageReaderWriterProvider.writeTo(AbstractMessageReaderWriterProvider.java:79)
        at org.glassfish.jersey.message.internal.InputStreamProvider.writeTo(InputStreamProvider.java:105)
        at org.glassfish.jersey.message.internal.InputStreamProvider.writeTo(InputStreamProvider.java:60)
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.invokeWriteTo(WriterInterceptorExecutor.java:265)
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.aroundWriteTo(WriterInterceptorExecutor.java:250)
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:162)
        at org.glassfish.jersey.message.internal.MessageBodyFactory.writeTo(MessageBodyFactory.java:1130)
        at org.glassfish.jersey.client.ClientRequest.doWriteEntity(ClientRequest.java:517)
        at org.glassfish.jersey.client.ClientRequest.writeEntity(ClientRequest.java:499)
        at org.glassfish.jersey.client.internal.HttpUrlConnector._apply(HttpUrlConnector.java:393)
        at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:285)
        ... 32 more

**Comment by priteshkp** [comment]
@ekumen UploadManager assumes you are not modifying the file while it's attempting to upload it.  It will attempt to upload the number of bytes that the File reports when you start the upload, if the file is modified while uploading, it won't work.

If you need to upload only the first part of a file while appending to it in the meantime, I would recommending using the other source that provides an InputStream and content length, and provide your own stream that reads just those bytes from the file.

**Comment by priteshkp** [comment]
Also, if you could provide a simple repro and attach here that would be great.

**Comment by ekumen** [comment]
@priteshkp Thanks for your reply!
OK, I will use InputStream and content length API, though it is a pity for me that I can't use UploadManager in this case. I try to copy our log file to ObjectStorage. If UploadManager can accept a content length parameter to limit uploading size that would be great.

**Comment by priteshkp** [comment]
You could still use `UploadManager` efficiently if you can buffer the file into memory.  Use `UploadRequestBuilder.builder(InputStream, long)` instead of `UploadRequestBuilder.builder(File)`.

Provide the InputStream by reading N bytes from your file into a `byte[]`, and create the `InputStream` using `StreamUtils.createByteArrayInputStream(byte[])`.  That should let you take advantage of the chunking and parallel upload capabilities of `UploadManager`.  It would be up to you to make sure that you're able to buffer into memory though (set heap size accordingly).
